openapi: 3.0.1
info:
  title: Zoom API
  description: |-
    The Zoom API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials).
    All endpoints are available via `https` and are located at `api.zoom.us/v2/`.

    For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  contact:
    name: Zoom Developers
    url: https://developer.zoom.us/
    email: developersupport@zoom.us
  license:
    name: MIT for OAS 2.0
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
servers:
  - url: https://api.zoom.us/v2
security:
  - OAuth: []
tags:
  - name: Accounts
    description: Account operations
  - name: Billing
    description: Billing operations
  - name: Chat Channels
  - name: Chat Channels (Account-level)
  - name: Chat Messages
    description: Chat Messages operations
  - name: Chatbot Messages
  - name: Contacts
    description: Contacts operations
  - name: Cloud Recording
    description: Cloud Recording operations
  - name: Dashboards
    description: Dashboard operations
  - name: Data Compliance
  - name: Devices
    description: H323 Device operations
  - name: Groups
    description: Group operations
  - name: IM Chat
    description: IM Chat operations
  - name: IM Groups
    description: IM Group operations
  - name: Meetings
    description: Meeting operations
  - name: PAC
    description: PAC operations
  - name: Phone
  - name: Phone Auto Receptionists
  - name: Phone Blocked List
  - name: Phone Call Queues
  - name: Phone Devices
  - name: Phone Reports
  - name: Phone Shared Line Groups
  - name: Phone Site
  - name: Common Area Phones
  - name: Reports
    description: Report operations
  - name: Roles
    description: User Roles
  - name: Rooms
    description: ZoomRooms operations
  - name: Rooms Account
  - name: Rooms Location
  - name: SIP Phone
  - name: TrackingField
    description: Tracking Field operations
  - name: TSP
    description: TSP operations
  - name: Users
    description: User operations
  - name: Webhooks
    description: Webhook operations
  - name: Webinars
    description: Webinar operations
  - name: master account APIs
    description: APIs available to the master account for a Zoom account.
  - name: Rooms Devices
  - name: SIP Connected Audio
  - name: Deprecated API Endpoints
paths:
  /accounts/{accountId}/phone/setup:
    post:
      tags:
        - Phone
      summary: Set up a Zoom Phone account
      description: |+
        After assigning a Zoom phone license to an account, an admin or account owner can proceed with the [initial Zoom phone set up](https://support.zoom.us/hc/en-us/articles/360001297663-Getting-started-with-Zoom-Phone-admin-#h_5ae26a3a-290c-4a8d-b3b0-6384ed267b13) using this API.

        **Scope**:<br>
        * `phone:write:admin` `phone:write`

        **Prerequisites**: <br>
        * Pro or a higher paid account with master account option enabled.

        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: setUpAccount
      security:
        - OAuth: []
  /phone/numbers:
    get:
      tags:
        - Phone
      summary: List phone numbers
      description: |-
        A Zoom account owner or admin can purchase phone numbers and assign them to Zoom phone users. Use this API to list all Zoom Phone numbers in a Zoom account. You can filter the response based on your needs by using query parameters.

        **Prerequisites:**<br>
        * Pro or higher plan with Zoom phone license<br>
        **Scope:** `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listAccountPhoneNumbers
      security:
        - OAuth: []
  /sip_phones:
    get:
      tags:
        - SIP Phone
      summary: List SIP phones
      description: |
        Zoom’s Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to list SIP phones on an account.<br><br>
        **Prerequisites**:
        * Currently only supported on Cisco and Avaya PBX systems.
        * User must enable SIP Phone Integration by contacting the [Sales](https://zoom.us/contactsales) team.<br> **Scope:** `sip_phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
      operationId: listSipPhones
      security:
        - OAuth: []
    post:
      tags:
        - SIP Phone
      summary: Enable SIP phone
      description: |+
        Zoom’s Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to enable a user to use SIP phone.<br><br>
        **Prerequisites**:
        * Currently only supported on Cisco and Avaya PBX systems.
        * The account owner or account admin must first enable SIP Phone Integration by contacting the [Sales](https://zoom.us/contactsales) team.<br> **Scope:** `sip_phone:write:admin`
        <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: createSIPPhone
      security:
        - OAuth: []
  /sip_phones/{phoneId}:
    delete:
      tags:
        - SIP Phone
      summary: Delete SIP phone
      description: |-
        Zoom’s Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to delete a specific SIP phone on a Zoom account.<br><br>
        **Prerequisites**:
        * Currently only supported on Cisco and Avaya PBX systems.
        * User must enable SIP Phone Integration by contacting the [Sales](https://zoom.us/contactsales) team.<br> **Scope:** `sip_phone:read:admin`
        <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: deleteSIPPhone
      security:
        - OAuth: []
    patch:
      tags:
        - SIP Phone
      summary: Update SIP phone
      description: |-
        Zoom’s Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to update information of a specific SIP Phone on a Zoom account.<br><br>
        **Prerequisites**:
        * Currently only supported on Cisco and Avaya PBX systems.
        * The account owner or account admin must first enable SIP Phone Integration by contacting the [Sales](https://zoom.us/contactsales) team.<br> **Scope:** `sip_phone:write:admin`
        <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: updateSIPPhone
      security:
        - OAuth: []
  /rooms:
    get:
      tags:
        - Rooms
      summary: List Zoom Rooms
      description: |-
        Zoom Rooms is a software-based room system that provides an integrated experience for audio conferencing, wireless screen sharing and video conferencing. Use this API to list all the existing [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343-Getting-Started-with-Zoom-Rooms) in a Zoom account.<br><br>
        **Prerequisites:**<br>
        * Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>
        **Scopes**: `room:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listZoomRooms
      security:
        - OAuth: []
    post:
      tags:
        - Rooms
      summary: Add a Zoom Room
      description: |-
        Use this API to [add a Zoom Room](https://support.zoom.us/hc/en-us/articles/202822279-Add-Zoom-Rooms-on-Web-Portal) to a Zoom account.<br><br>
        **Prerequisites:**<br>
        * Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>
        **Scopes**: `room:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: addARoom
      security:
        - OAuth: []
  /phone/sites:
    get:
      tags:
        - Phone Site
      summary: List phone sites
      description: |-
        Sites allow you to organize Zoom Phone users in your organization. Use this API to list all the [sites](https://support.zoom.us/hc/en-us/articles/360020809672) that have been created for an account.<br>
        **Prerequisites:**<br>
        * Multiple Sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).
        * Pro or a higher account with Zoom Phone enabled.

        **Scope:** `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listPhoneSites
    post:
      tags:
        - Phone Site
      summary: Create a phone site
      description: |+
        Sites allow you to organize Zoom Phone users in your organization. Use this API to create a [Site](https://support.zoom.us/hc/en-us/articles/360020809672).<br>
        **Prerequisites:**<br>
        * Multiple Sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).
        * Pro or a higher account with Zoom Phone enabled.
        **Scope:** `phone:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: createPhoneSite
      security:
        - OAuth: []
  /phone/sites/{siteId}:
    get:
      tags:
        - Phone Site
      summary: Get phone site details
      description: |+
        Sites allow you to organize Zoom Phone users in your organization. Use this API to get information about a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672).


        **Prerequisites:** <br>
        * Account must have a Pro or a higher plan with Zoom Phone license.
        * Multiple Sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).<br>
        **Scope:** `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: getASite
      security:
        - OAuth: []
    delete:
      tags:
        - Phone Site
      summary: Delete a phone site
      description: |+
        Sites allow you to organize Zoom Phone users in your organization. Use this API to delete a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672) in a Zoom account. To delete a site, in the query parameter, you must provide the Site ID of another site where the assets of current site (users, numbers and phones) can be transferred to.  You cannot use this API to delete the main site.

        **Prerequisites:** <br>
        * Account must have a Pro or a higher plan with Zoom Phone license.
        * [Multiple Sites](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites) must be enabled.<br>
        **Scope:** `phone:write:admin`
        <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: deletePhoneSite
      security:
        - OAuth: []
    patch:
      tags:
        - Phone Site
      summary: Update phone site details
      description: |+
        Sites allow you to organize Zoom Phone users in your organization. Use this API to update information about a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672).


        **Prerequisites:** <br>
        * Account must have a Pro or a higher plan with Zoom Phone license.
        * **Scope:** `phone:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: updateSiteDetails
      security:
        - OAuth: []
  /phone/sms/messages:
    post:
      tags:
        - Phone
      summary: Post SMS message
      description: |-
        Send [SMS messages ](https://support.zoom.us/hc/en-us/articles/360054631031-Setting-up-SMS) to Zoom Phone accounts.

        **Scope:**
        * `phone_sms:write`
        * `phone_sms:write:admin`

        **Prerequisites:**
        * Zoom Phone license
        * SMS enabled for the account or admin privileges
        * User-enabled Zoom Phone

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

        **SMS and Attachments - Size and Limits:**
        * SMS size with no media attachments: 2048 bytes
        * SMS size with attachments: 1000 bytes
        * Total attachments: 10
        * Total attachments file size: 2MB
      operationId: postSmsMessage
      x-private: true
  /contacts:
    get:
      tags:
        - Contacts
      summary: Search company contacts
      description: |-
        A user under an organization's Zoom account has internal users listed under Company Contacts in the Zoom Client. Use this API to search users that are in the company contacts of a Zoom account. Using the `search_key` query parameter, provide either first name, last name or the email address of the user that you would like to search for. Optionally, set `query_presence_status` to `true` in order to include the presence status of a contact. <br><br>

        **Scopes:** `contact:read:admin`, `contact:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: searchCompanyContacts
  /chat/users/{userId}/messages:
    get:
      tags:
        - Chat Messages
      summary: List user's chat messages
      description: |+
        A Zoom user can have conversations with other Zoom users via chat. Use this API to list the current user's chat messages between the user and an individual contact or a chat channel.<br> In the query parameter, you must provide either of the following:<br>
        * `to_contact`: The email address of the contact with whom the user conversed by sending/receiving messages.
        * `to_channel`: The channel ID of the channel to/from which the user has sent and/or received messages.

        <br> **Specify a date** in the `date` query parameter to view messages from that date. If a date is not provided, the default value for the query will be the **current date**.<br>
        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20enab[...]

        <br>**Scopes:** `chat_message:read`, `chat_message:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`

      operationId: getChatMessages
      security:
        - OAuth: []
    post:
      tags:
        - Chat Messages
      summary: Send a chat message
      description: |+
        Send chat messages on Zoom to either an individual user who is in your contact list or to a [channel](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) of which you are a member. To send a message to a contact, provide the contact's email address in the `to_contact` field. Similary, to send a message to a channel, provide the Channel Id of the Channel in `to_channel` field.<br>
        <br>**Scopes:** `chat_message:write`, `chat_message:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br> <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <b><a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Ea[...]

      operationId: sendaChatMessage
      security:
        - OAuth: []
  /chat/users/{userId}/messages/{messageId}:
    put:
      tags:
        - Chat Messages
      summary: Update a message
      description: "Each chat message has a unique identifier. Use this API to edit\
        \ a chat message that you previously sent to either a contact or a channel\
        \ in Zoom by providing the ID of the message as the value of the `messageId`\
        \ parameter. The ID can be retrieved from List User's Chat Messages API. Additionally,\
        \ as a query parameter, you must provide either the **email address** of the\
        \ contact or the **Channel ID** of the channel where the message was sent.\
        \ \n\n**Scope:** `chat_message:write`,`chat_message:write:admin`\t<br>\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium` \n\n</b> For an<b> account-level</b> <a href=\"https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app\"\
        >OAuth app</a>, this API can only be used on behalf of a user who is assigned\
        \ with a <b><a href=\"https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20enables,needs%20to%20view%20or%20edit.\"\
        > role</a> that has Edit permission for Chat Messages</b>.</p>\n**Scope:**\
        \ `chat_message:write`, `chat_message:write:admin`<br>\n\n\n\n\n\n\n"
      operationId: editMessage
      security:
        - OAuth: []
    delete:
      tags:
        - Chat Messages
      summary: Delete a message
      description: |-
        Delete a chat message that you previously sent to a contact or a channel. In the query parameter, you must provide either of the following:<br>
        * `to_contact`: The email address of the contact to whom you sent the message. Use this parameter to delete a message sent to an individual contact in Zoom.
        * `to_channel`: The channel ID of the channel where you sent the message. Use this parameter to delete a message sent to a channel in Zoom.

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <b><a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20e[...]

        **Scope:** `chat_message:write`, `chat_message:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: deleteChatMessage
      security:
        - OAuth: []
  /chat/users/{userId}/channels:
    get:
      tags:
        - Chat Channels
      summary: List user's channels
      description: |-
        Zoom chat [channels](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) allow users to communicate via chat in private or public groups. Use this API to list a user's chat channels.

        **Scope**: `chat_channel:read` or `chat_channel:read:admin`<br>
        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API supports both user-managed apps and account-level apps. However, in an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, to list channels of another user in the same Zoom account, the user calling this API must have a <a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%2[...]




         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getChannels
      security:
        - OAuth: []
    post:
      tags:
        - Chat Channels
      summary: Create a channel
      description: |
        Zoom chat channels allow users to communicate via chat in private or public groups. Use this API to create a channel for a user.<br>
        **Scopes**:`chat_channel:write` or `chat_channel:write:admin`<br>

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API supports both user-managed apps and account-level apps. However, in an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, to create a channel on behalf of another user in the same Zoom account, the user calling this API must have a <a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=[...]

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: createChannel
      security:
        - OAuth: []
  /chat/users/me/contacts:
    get:
      tags:
        - Contacts
      summary: List user's contacts
      description: |-
        A user under an organization’s Zoom account has internal users listed under Company Contacts in the Zoom Client. A Zoom user can also add another Zoom user as a [contact](https://support.zoom.us/hc/en-us/articles/115004055706-Managing-Contacts). Call this API to list all the contacts of a Zoom user. Zoom contacts are categorized into "company contacts" and "external contacts". You must specify the contact type in the `type` query parameter. If you do not specify, by default, the type wil[...]

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>

        **Scope**: `chat_contact:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getUserContacts
      security:
        - OAuth: []
  /chat/users/me/contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Get user's contact details
      description: |-
        A user under an organization’s Zoom account has internal users listed under Company Contacts in the Zoom Client. A Zoom user can also add another Zoom user as a [contact](https://support.zoom.us/hc/en-us/articles/115004055706-Managing-Contacts). Call this API to get information on a specific contact of the Zoom user.

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b>This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>

        **Scope**: `chat_contact:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getUserContact
      security:
        - OAuth: []
  /chat/users/{userId}/channels/{channelId}:
    get:
      tags:
        - Chat Channels (Account-level)
      summary: Get a channel
      description: |-
        Zoom chat [channels](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) allow users to communicate via chat in private or public groups. Use this API to get information about a specific channel.

        **Scope:** `chat_channel:read:admin` <br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` <br>

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <b> <a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20[...]
      operationId: getChannel
      security:
        - OAuth: []
    delete:
      tags:
        - Chat Channels (Account-level)
      summary: Delete a channel
      description: |-
        Zoom chat [channels](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) allow users to communicate via chat in private or public groups. Use this API to delete a specific channel.

        **Scope:** `chat_channel:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>
      operationId: deleteChannel
    patch:
      tags:
        - Chat Channels (Account-level)
      summary: Update a channel
      description: "Zoom chat channels allow users to communicate via chat in private\
        \ or public channels. Use this API to update the name of a specific channel\
        \ created by a user. <br><br>\n**Scope:** `chat_channel:write:admin`\t<br>\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`\n<p style=\"background-color:#e1f5fe; color:#01579b; padding:8px\"\
        > <b>Note: </b> For an<b> account-level</b> <a href=\"https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app\"\
        >OAuth app</a>, this API can only be used on behalf of a user who is assigned\
        \ with a <b> <a href=\"https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20enables,needs%20to%20view%20or%20edit.\"\
        > role</a>  that has Edit permission for Chat Channel</b>.</p>\n"
      operationId: updateChannel
      security:
        - OAuth: []
  /chat/users/{userId}/channels/{channelId}/members:
    get:
      tags:
        - Chat Channels (Account-level)
      summary: List channel members
      description: |-
        A [channel](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) can have one or multiple members. List all the members of a channel using this API.

         </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <b><a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20enables,needs%20to%20view%20or%20edit."> role</a> that has View or Edit pe[...]

        **Scopes:** `chat_channel:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listChannelMembers
      security:
        - OAuth: []
    post:
      tags:
        - Chat Channels (Account-level)
      summary: Invite channel members
      description: |-
        A [channel](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) can have one or multiple members. Use this API to invite members that are in a user's contact list to a channel. The maximum number of members that can be added at once with this API is 5.

        **Scope:** `chat_channel:write:admin` <br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`

         </b> For an<b> account-level</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>, this API can only be used on behalf of a user who is assigned with a <b><a href="https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management#:~:text=Each%20user%20in%20a%20Zoom,owner%2C%20administrator%2C%20or%20member.&text=Role%2Dbased%20access%20control%20enables,needs%20to%20view%20or%20edit."> role</a> that has Edit permission[...]
      operationId: inviteChannelMembers
      security:
        - OAuth: []
  /chat/channels/{channelId}:
    get:
      tags:
        - Chat Channels
      summary: Get a channel
      description: "Zoom chat [channels](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-)\
        \ allow users to communicate via chat in private or public groups. Use this\
        \ API to get information about a specific channel. \n\n**Scope:** `chat_channel:read`\t\
        <br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`\n\n<p style=\"background-color:#e1f5fe; color:#01579b; padding:8px\"\
        > <b>Note: </b> This API only supports <b>user-managed</b> <a href=\"https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app\"\
        >OAuth app</a>.</p><br>\n\n\n "
      operationId: getUserLevelChannel
      security:
        - OAuth: []
    delete:
      tags:
        - Chat Channels
      summary: Delete a channel
      description: |-
        Zoom chat [channels](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) allow users to communicate via chat in private or public groups. Use this API to delete a specific channel.

        **Scope:** `chat_channel:write`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>
      operationId: deleteUserLevelChannel
    patch:
      tags:
        - Chat Channels
      summary: Update a channel
      description: "Zoom chat channels allow users to communicate via chat in private\
        \ or public channels. Use this API to update the name of a specific channel\
        \ that you created. \n\n**Scope:** `chat_channel:write`\t<br>\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`\n\n<p style=\"background-color:#e1f5fe; color:#01579b; padding:8px\"\
        > <b>Note: </b> This API only supports <b>user-managed</b> <a href=\"https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app\"\
        >OAuth app</a>.</p><br>\n\n"
      operationId: updateUserLevelChannel
      security:
        - OAuth: []
  /chat/channels/{channelId}/members/{memberId}:
    delete:
      tags:
        - Chat Channels
      summary: Remove a member
      description: |2+
         A [channel](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) can have one or multiple members. Use this API to remove a member from a chat channel.<br><br>
         **Scopes:** `chat_channel:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`

         <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b> This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>


      operationId: removeAUserLevelChannelMember
      security:
        - OAuth: []
  /chat/channels/{channelId}/members/me:
    post:
      tags:
        - Chat Channels
      summary: Join a channel
      description: |-
        A [channel](https://support.zoom.us/hc/en-us/articles/200912909-Getting-Started-With-Channels-Group-Messaging-) can have one or multiple members. Use this API to join a channel that is open for anyone in the same organization to join. You cannot use this API to join private channels that only allows invited members to be a part of it.

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b>This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>

        **Scope:** `chat_channel:write`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: joinChannel
      security:
        - OAuth: []
    delete:
      tags:
        - Chat Channels
      summary: Leave a channel
      description: |-
        If you're no longer interested in being a member of an existing channel, you can leave the channel at any time. Use this API to leave a specific channel. After leaving the channel, you can no longer access information from that channel.

        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b>This API only supports <b>user-managed</b> <a href="https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-oauth-app">OAuth app</a>.</p><br>

        **Scope:** `chat_channel:write`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: leaveChannel
      security:
        - OAuth: []
  /accounts:
    get:
      tags:
        - Accounts
      summary: List sub accounts
      description: |+
        List all the sub accounts that have been created by a master account.<br><br>Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts. Email the partner programs team at **partner-success@zoom.us** for more details.

        <br>**Prerequisites:**<br>
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope**: `account:read:admin`
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

      operationId: accounts
    post:
      tags:
        - Accounts
      summary: Create a sub account
      description: |-
        Create a sub account under a master account. Your account must be a master account in order to create sub accounts.
        <br><br>Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts. Email the partner programs team at partner-success@zoom.us. for more details. Please note that the created account user will receive a confirmation email.<br><br>
        <br>
        **Prerequisites:**<br>
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope**: `account:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: accountCreate
  /accounts/{accountId}:
    get:
      tags:
        - Accounts
      summary: Get sub account details
      description: |
        Get details of a sub account that is listed under a master account. Your account must be a master account in order to retrieve sub accounts' details. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and create sub accounts. Email the partner programs team at **partner-success@zoom.us** for more details.

        **Prerequisites:**
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope**: `account:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: account
    delete:
      tags:
        - Accounts
      summary: Disassociate a sub account
      description: |-
        Disassociate a sub account from its master account. This will leave the sub account intact but it will no longer be associated with the master account.<br>

        **Prerequisites:**
        * Pro or a higher paid account with master account option enabled. <br>
        * The account making this API request must be a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis).<br><br>


        **Scope**: `account:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: accountDisassociate
  /accounts/{accountId}/options:
    patch:
      tags:
        - Accounts
      summary: Update options
      description: |-
        Update a sub account's options under the master account.<br> <aside>Your account must be a master account in order to update the options for sub accounts. Zoom only assigns this privilege to trusted partners. </aside>

        **Prerequisites:**
        * Pro or a higher paid account with master account option enabled.
        * The account making this API request must be a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis).<br><br>

        **Scope**: `account:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: accountOptionsUpdate
      security:
        - OAuth: []
  /accounts/{accountId}/settings:
    get:
      tags:
        - Accounts
      summary: Get settings
      description: |-
        Get the settings of an account.<br>
        To get the settings of a master account, use `me` as the value for the `accountId` path parameter.<br><br>
         **Prerequisites**:
         * The account must be a paid account.<br>
        **Scopes**: `account:read:admin`
        <br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: accountSettings
    patch:
      tags:
        - Accounts
      summary: Update settings
      description: |-
        Update the settings of a sub account that is under a master account.<br> To update the settings of the master account, use `me` as the value of the `accountId` path parameter.<br><br>
        **Prerequisites**:
         * The sub account must be a paid account.<br>
        **Scopes**: `account:write:admin`
        <br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: accountSettingsUpdate
  /accounts/{accountId}/managed_domains:
    get:
      tags:
        - Accounts
      summary: Get managed domains
      description: |+
        Get a sub account's [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Domain-).<br><br>

        **Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts options enabled. <br><br>
        To get managed domains of the master account, provide `me` as the value for accountId in the path parameter. Provide the sub account's Account ID as the value of accountId path parameter to get managed domains of the sub account.<br><br>
        **Prerequisites:**<br>
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope:** `account:read:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>



      operationId: accountManagedDomain
      security:
        - OAuth: []
  /accounts/{accountId}/trusted_domains:
    get:
      tags:
        - Accounts
      summary: Get trusted domains
      description: |-
        Get trusted domains of a sub account. To get the trusted domains of a master account, use `me` as the value for the `accountId` path parameter.

        **Prerequisites:**<br>
        * The sub account must be a paid account.<br>
        **Scope:** `account:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: accountTrustedDomain
  /accounts/{accountId}/billing:
    get:
      tags:
        - Billing
      summary: Get billing information
      description: |+
        Get [billing information](https://support.zoom.us/hc/en-us/articles/201363263-About-Billing) of a sub account.<br><br>Only master accounts can use this API. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more details.<br>

        **Prerequisites:**
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope**:`billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

      operationId: accountBilling
    patch:
      tags:
        - Billing
      summary: Update billing information
      description: |+
        Update [billing information](https://support.zoom.us/hc/en-us/articles/201363263-About-Billing) of a sub account.<br><br>
        This API can only be used by master accounts that pay all billiing charges of their associated sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>

        **Prerequisites:**
        * Pro or a higher paid account with master account option enabled. <br>

        **Scope**:`billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>

      operationId: accountBillingUpdate
  /accounts/{accountId}/plans:
    get:
      tags:
        - Billing
      summary: Get plan Information
      description: |-
        Get plan information of a sub account that is managed by a master account. <br><br>This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>
        **Scopes:** `billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
      operationId: accountPlans
    post:
      tags:
        - Billing
      summary: Subscribe plans
      description: |-
        Subscribe a sub account to a Zoom plan using your master account. This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>
        **Scopes**: `billing:master`<br>
      operationId: accountPlanCreate
  /accounts/{accountId}/plans/base:
    put:
      tags:
        - Billing
      summary: Update a base plan
      description: |-
        Update a base plan of a sub account.

        This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>
        **Scopes:** `billing:master`<br><br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * The sub account must have a Pro or a higher plan.
      operationId: accountPlanBaseUpdate
  /accounts/{accountId}/plans/addons:
    put:
      tags:
        - Billing
      summary: Update an additional plan
      description: |-
        Update an additional plan for a sub account.

        This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>
        <br>**Prerequisites:**<br>
        * Pro or a higher plan with master account enabled.
        * The sub account must be a paid account. The billing charges for the sub account must be paid by the master account.<br><br>

        **Scopes**: `billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
      operationId: accountPlanAddonUpdate
    post:
      tags:
        - Billing
      summary: Subscribe additional plan
      description: |+
        Subscribe a sub account to a Zoom addon plan. This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>
        <br>**Prerequisites:**<br>
        * Pro or a higher plan with master account option enabled.
        * The sub account must be a paid account. The billing charges for the sub account must be paid by its master account.<br><br>

        **Scopes**: `billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>

      operationId: accountPlanAddonCreate
  /groups:
    get:
      tags:
        - Groups
      summary: List groups
      description: |-
        List [groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.

        **Prerequisite**: Pro or higher account.<br>
        **Scopes**: `group:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: groups
      security:
        - OAuth: []
    post:
      tags:
        - Groups
      summary: Create a group
      description: |-
        Create a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.

        You can add a maximum of 100 groups in one account per day. If you go over, you will get an error. You can add a maximum of 5000 groups in one account.

        **Prerequisite**: Pro or higher account.<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: groupCreate
      security:
        - OAuth: []
  /groups/{groupId}:
    get:
      tags:
        - Groups
      summary: Get a group
      description: |-
        Get a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: group
      security:
        - OAuth: []
    delete:
      tags:
        - Groups
      summary: Delete a group
      description: |-
        Delete a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: groupDelete
      security:
        - OAuth: []
    patch:
      tags:
        - Groups
      summary: Update a group
      description: |-
        Update a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: groupUpdate
      security:
        - OAuth: []
  /groups/{groupId}/members:
    get:
      tags:
        - Groups
      summary: 'List group members '
      description: |-
        List the members of a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: groupMembers
      security:
        - OAuth: []
    post:
      tags:
        - Groups
      summary: Add group members
      description: |-
        Add members to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: groupMembersCreate
  /groups/{groupId}/members/{memberId}:
    delete:
      tags:
        - Groups
      summary: Delete a group member
      description: |-
        Delete a member from a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in a Zoom account.

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: groupMembersDelete
      security:
        - OAuth: []
    patch:
      tags:
        - Groups
      summary: Update a group member
      description: |-
        If a user is a member in multiple groups, you can [set a primary group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-#h_d07c7dcd-4fd8-485a-b5fe-a322e8d21c09) for the user. The group member will use the primary group's settings by default. However, if settings are locked in other groups, those settings will continue to be locked for that user. By default, the primary group is the first group that user is added to.<br><br>
        Use this API to perform either of the following tasks:
        * Simultaneously remove a member from one group and move the member to a different group.
        * Set a primary group for the user<br><br>
        **Prerequisites:**
        * Pro or higher account<br> **Scopes:** `group:write:admin`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateAGroupMember
      security:
        - OAuth: []
  /h323/devices:
    get:
      tags:
        - Devices
      summary: List H.323/SIP devices
      description: |-
        A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to list all H.323/SIP Devices on a Zoom account.<br><br>
        **Scopes:** `h323:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
      operationId: deviceList
      security:
        - OAuth: []
    post:
      tags:
        - Devices
      summary: Create a H.323/SIP device
      description: |-
        A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to add a H.323/SIP device to your Zoom account<br><br>
        **Scopes:** `h323:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>
      operationId: deviceCreate
      security:
        - OAuth: []
  /h323/devices/{deviceId}:
    delete:
      tags:
        - Devices
      summary: Delete a H.323/SIP device
      description: |-
        A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to delete a H.323/SIP device from your Zoom account.<br><br>
        **Scopes:** `h323:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: deviceDelete
    patch:
      tags:
        - Devices
      summary: Update a H.323/SIP device
      description: |-
        A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to edit information of a H.323/SIP device from your Zoom account.<br><br>
        **Scopes:** `h323:write:admin`<br>
         <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: deviceUpdate
  /tracking_fields:
    get:
      tags:
        - TrackingField
      summary: List tracking fields
      description: |-
        [Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to list all the tracking fields on your Zoom account.<br><br>
        **Scopes:** `trackingfield:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites:**
        * Business, Education, API or higher plan
      operationId: trackingfieldList
      security:
        - OAuth: []
    post:
      tags:
        - TrackingField
      summary: Create a tracking field
      description: |-
        [Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to create a new tracking field.<br><br>
        **Scope:** `trackingfield:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Business, Education, API or higher plan
      operationId: trackingfieldCreate
      security:
        - OAuth: []
  /tracking_fields/{fieldId}:
    get:
      tags:
        - TrackingField
      summary: Get a tracking field
      description: |
        [Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br><br> When scheduling a meeting, the tracking field will be included in the meeting options.<br>Use this API to get information on a tracking field.<br><br>
        **Scopes:** `trackingfield:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Business, Education, API or higher plan
      operationId: trackingfieldGet
      security:
        - OAuth: []
    delete:
      tags:
        - TrackingField
      summary: Delete a tracking field
      description: |-
        [Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to delete a tracking field.<br><br>
        **Scope:** `trackingfield:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Business, Education, API or higher plan
      operationId: trackingfieldDelete
      security:
        - OAuth: []
    patch:
      tags:
        - TrackingField
      summary: Update a tracking field
      description: |-
        [Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to update a tracking field.<br><br>
        **Scope:** `trackingfield:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Business, Education, API or higher plan
      operationId: trackingfieldUpdate
      security:
        - OAuth: []
  /im/groups:
    get:
      tags:
        - IM Groups
      summary: List IM directory groups
      description: |-
        List [IM directory groups](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).<br><br>
        **Scopes**: `imgroup:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: imGroups
    post:
      tags:
        - IM Groups
      summary: Create an IM directory group
      description: |-
        Create an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>
        **Scopes**: `imgroup:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: imGroupCreate
  /im/groups/{groupId}:
    get:
      tags:
        - IM Groups
      summary: Retrieve an IM directory group
      description: |-
        Retrieve an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>
        Scopes: `imgroup:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: imGroup
    delete:
      tags:
        - IM Groups
      summary: Delete an IM directory group
      description: |-
        Delete an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>
        Scopes: `imgroup:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: imGroupDelete
    patch:
      tags:
        - IM Groups
      summary: Update an IM directory group
      description: |-
        Update an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>
        **Scopes**: `imgroup:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: imGroupUpdate
  /im/groups/{groupId}/members:
    get:
      tags:
        - IM Groups
      summary: List IM directory group members
      description: |-
        List the members of an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).<br><br>
        **Scope:** `imgroup:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: imGroupMembers
      security:
        - OAuth: []
    post:
      tags:
        - IM Groups
      summary: Add IM directory group members
      description: |-
        Add members to an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.<br><br>
        **Scope:** `imgroup:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: imGroupMembersCreate
      security:
        - OAuth: []
  /im/groups/{groupId}/members/{memberId}:
    delete:
      tags:
        - IM Groups
      summary: Delete an IM directory group member
      description: |-
        Delete a member from an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.<br><br>
        Scopes: `imgroup:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: imGroupMembersDelete
      security:
        - OAuth: []
  /im/chat/sessions:
    get:
      tags:
        - IM Chat
      summary: Get IM chat sessions
      description: |-
        Retrieve IM Chat sessions for a specified period of time. <aside>Note: This API only supports Oauth2.</aside><br>

        **Scopes:** `imchat:read, imchat:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`

         Please see our [announcements page related to this deprecation](https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#im-api-notice).
      operationId: imChatSessions
      deprecated: true
      security:
        - OAuth: []
  /im/chat/sessions/{sessionId}:
    get:
      tags:
        - IM Chat
      summary: Get IM chat messages
      description: |+
        Retrieve IM chat messages for a specified period of time. <aside>Note: This API only supports oauth2.</aside><br><br>

        **Scopes:** `imchat:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

        Please see our [announcements page related to this deprecation](https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#im-api-notice).


      operationId: imChatMessages
      deprecated: true
  /users/{userId}/meetings:
    get:
      tags:
        - Meetings
      summary: List meetings
      description: |-
        List all the meetings that were scheduled for a user (meeting host). This API only supports scheduled meetings and thus, details on instant meetings are not returned via this API.<br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: meetings
      security:
        - OAuth: []
    post:
      tags:
        - Meetings
      summary: Create a meeting
      description: "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)\
        \ for a user. <br>This API has a daily rate limit of 100 requests per day.\
        \ Therefore, only 100 **Create a Meeting** API requests are permitted within\
        \ a 24 hour window for a user.<br>\n\n<aside>The <code>start_url</code> of\
        \ a meeting is a URL using which a host or an alternative host can start a\
        \ meeting. The expiration time for the <code>start_url</code> field is two\
        \ hours for all regular users. \n\t\nFor custCreate meeting hosts( i.e., users\
        \ created using the <code>custCreate</code> option via the [Create Users](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate)\
        \ API), the expiration time of the <code>start_url</code> field is 90 days\
        \ from the generation of the <code>start_url</code>.\n\t\nFor security reasons,\
        \ the recommended way to retrieve the updated value for the <code>start_url</code>\
        \ field programmatically (after expiry) is by calling the [Retrieve a Meeting\
        \ API](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meeting)\
        \ and referring to the value of the <code>start_url</code> field in the response.</aside><br><br>\n\
        Scopes: `meeting:write:admin` `meeting:write`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: meetingCreate
  /meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting
      description: |+
        Retrieve the details of a meeting.<br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meeting
      security:
        - OAuth: []
    delete:
      tags:
        - Meetings
      summary: Delete a meeting
      description: |+
        Delete a meeting.<br><br>
        **Scopes:** `meeting:write:admin` `meeting:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingDelete
      security:
        - OAuth: []
    patch:
      tags:
        - Meetings
      summary: Update a meeting
      description: |+
        Update the details of a meeting.<br>This API has a rate limit of 100 requests per day. Therefore, a meeting can only be updated for a maximum of 100 times within a 24 hour window.<br>
        **Scopes:** `meeting:write:admin` `meeting:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingUpdate
      security:
        - OAuth: []
  /meetings/{meetingId}/status:
    put:
      tags:
        - Meetings
      summary: Update meeting status
      description: |-
        Update the status of a meeting.<br><br>
        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: meetingStatus
      security:
        - OAuth: []
  /meetings/{meetingId}/registrants:
    get:
      tags:
        - Meetings
      summary: List meeting registrants
      description: |-
        A host or a user with admin permission can require [registration for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings). Use this API to list users that have registered for a meeting.<br><br>
        **Scopes**: `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: meetingRegistrants
      security:
        - OAuth: []
    post:
      tags:
        - Meetings
      summary: Add meeting registrant
      description: |-
        Register a participant for a meeting.<br><br> Note that there is a maximum limit of 4999 registrants per meeting and users will see an error if the capacity has reached.

        **Prerequisite:**<br>
        * Host user type must be "Licensed".

        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: meetingRegistrantCreate
      security:
        - OAuth: []
  /meetings/{meetingId}/registrants/{registrantId}:
    delete:
      tags:
        - Meetings
      summary: Delete a meeting registrant
      description: |-
        Delete a meeting registrant.<br><br>
        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: meetingregistrantdelete
  /meetings/{meetingId}/registrants/status:
    put:
      tags:
        - Meetings
      summary: Update registrant's status
      description: |-
        Update a meeting registrant's status by either approving, cancelling or denying a registrant from joining the meeting.<br><br>
        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: meetingRegistrantStatus
      security:
        - OAuth: []
  /past_meetings/{meetingUUID}:
    get:
      tags:
        - Meetings
      summary: Get past meeting details
      description: |-
        Get details on a past meeting. <br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
        > **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.
      operationId: pastMeetingDetails
      security:
        - OAuth: []
  /past_meetings/{meetingUUID}/participants:
    get:
      tags:
        - Meetings
      summary: Get past meeting participants
      description: |
        Retrieve information on participants from a past meeting. <br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
        **Prerequisites:**<br>
        * Paid account on a Pro or higher plan.

        <br> <br>  **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.
      operationId: pastMeetingParticipants
      security:
        - OAuth: []
  /past_meetings/{meetingId}/instances:
    get:
      tags:
        - Meetings
      summary: List ended meeting instances
      description: |-
        Get a list of ended meeting instances<br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: pastMeetings
      security:
        - OAuth: []
  /meetings/{meetingId}/polls:
    get:
      tags:
        - Meetings
      summary: List meeting polls
      description: |-
        Polls allow the meeting host to survey attendees. Use this API to list [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) of a meeting.<br><br>

        **Scopes**: `meeting:read:admin` `meeting:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>
        * Host user type must be **Pro** or higher plan.
        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: meetingPolls
      security:
        - OAuth: []
    post:
      tags:
        - Meetings
      summary: Create a meeting poll
      description: |-
        Polls allow the meeting host to survey attendees. Use this API to create a [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.<br><br>

        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>
        * Host user type must be **Pro** or higher plan.
        * Polling feature must be enabled in the host's account.
        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: meetingPollCreate
      security:
        - OAuth: []
  /meetings/{meetingId}/polls/{pollId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting poll
      description: |+
        Polls allow the meeting host to survey attendees. Use this API to get information about a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br><br>
        **Scopes**: `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


      operationId: meetingPollGet
      security:
        - OAuth: []
    put:
      tags:
        - Meetings
      summary: Update a meeting poll
      description: |+
        Polls allow the meeting host to survey attendees. Use this API to update information of a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)<br><br>
        **Scopes**: `meeting:write:admin` `meeting:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingPollUpdate
      security:
        - OAuth: []
    delete:
      tags:
        - Meetings
      summary: Delete a meeting poll
      description: |-
        Polls allow the meeting host to survey attendees. Use this API to delete a meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br>
        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>
        **Prerequisites**:<br>
        * Host user type must be **Pro**.
        * Polling feature should be enabled in the host's account.
        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: meetingPollDelete
      security:
        - OAuth: []
  /meetings/{meetingId}/registrants/questions:
    get:
      tags:
        - Meetings
      summary: 'List registration questions '
      description: |+
        List registration questions that will be displayed to users while [registering for a meeeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br>

        **Scopes:** `meeting:read`, `meeting:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingRegistrantsQuestionsGet
      security:
        - OAuth: []
    patch:
      tags:
        - Meetings
      summary: Update registration questions
      description: |+
        Update registration questions that will be displayed to users while [registering for a meeeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br><br>
        **Scopes:** `meeting:write`, `meeting:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


      operationId: meetingRegistrantQuestionUpdate
      security:
        - OAuth: []
  /users/{userId}/recordings:
    get:
      tags:
        - Cloud Recording
      summary: List all recordings
      description: |-
        When a user records a meeting or a webinar by choosing the **Record to the Cloud** option, the video, audio, and chat text are recorded in the Zoom cloud.

        Use this API to list all [Cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a user.<br>
        > To access a user's password protected cloud recording, add an "access_token" parameter to the download URL and provide either the [JWT](https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-jwt-app) or the user's OAuth access token as the value of the "access_token" parameter.
        <br>

        **Scopes:** `recording:read:admin` `recording:read`  <br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites:**
        * Pro or a higher plan.
        * Cloud Recording must be enabled on the user's account.
      operationId: recordingsList
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings:
    get:
      tags:
        - Cloud Recording
      summary: Get meeting recordings
      description: |+
        Get all the [recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording#h_7420acb5-1897-4061-87b4-5b76e99c03b4) from a meeting or Webinar instance.<br><br> The recording files can be downloaded via the `download_url` property listed in the response.

        > To access a password protected cloud recording, add an "access_token" parameter to the download URL and provide OAuth access token or [JWT](https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-jwt-app) as the value of the "access_token".
        <br>

        **Scopes:** `recording:read:admin` `recording:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: recordingGet
      security:
        - OAuth: []
    delete:
      tags:
        - Cloud Recording
      summary: Delete meeting recordings
      description: |
        Delete all recording files of a meeting.<br><br>

        **Scopes:** `recording:write:admin` `recording:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:
        * Cloud Recording should be enabled on the user's account.<br>
      operationId: recordingDelete
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/{recordingId}:
    delete:
      tags:
        - Cloud Recording
      summary: Delete a meeting recording file
      description: |-
        Delete a sprecific recording file from a meeting.<br><br>
        **Scopes**: `recording:write:admin` `recording:write`<br>
         <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: recordingDeleteOne
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/status:
    put:
      tags:
        - Cloud Recording
      summary: Recover meeting recordings
      description: |-
        Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover all deleted [Cloud Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a specific meeting.<br><br>
        **Scopes**: `recording:write:admin` `recording:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>
        * A Pro user with Cloud Recording enabled.
      operationId: recordingStatusUpdate
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/{recordingId}/status:
    put:
      tags:
        - Cloud Recording
      summary: Recover a single recording
      description: |
        Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover a single recording file from the meeting.<br>
        **Scopes:** `recording:write:admin` `recording:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: recordingStatusUpdateOne
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/settings:
    get:
      tags:
        - Cloud Recording
      summary: Get meeting recording settings
      description: |-
        Retrieve settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).<br><br>
        **Scopes**: `recording:read:admin` `recording:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>
      operationId: recordingSettingUpdate
      security:
        - OAuth: []
    patch:
      tags:
        - Cloud Recording
      summary: Update meeting recording settings
      description: |-
        Update settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)<br><br>
        **Scopes**: `recording:write:admin` `recording:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>
      operationId: recordingSettingsUpdate
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/registrants:
    get:
      tags:
        - Cloud Recording
      summary: List recording registrants
      description: |
        Cloud Recordings of past Zoom Meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings). Users should be [registered](https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/meetingrecordingregistrantcreate) to view these recordings.

        Use this API to list registrants of **On-demand Cloud Recordings** of a past meeting.<br>
        **Scopes:** `recording:read:admin`, `recording:read`.<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: meetingRecordingRegistrants
      security:
        - OAuth: []
    post:
      tags:
        - Cloud Recording
      summary: Create a recording registrant
      description: |+
        Cloud Recordings of past Zoom Meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings). Users should be [registered](https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/meetingrecordingregistrantcreate) to view these recordings.

        Use this API to register a user to gain access to **On-demand Cloud Recordings** of a past meeting.<br>
        **Scopes:** `recording:write:admin`, `recording:write`.<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingRecordingRegistrantCreate
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/registrants/status:
    put:
      tags:
        - Cloud Recording
      summary: Update registrant's status
      description: |
        A registrant can either be approved or denied from viewing the [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) recording.
        Use this API to update a registrant's status.

        **Scopes:** `recording:write:admin`, `recording:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: meetingRecordingRegistrantStatus
      security:
        - OAuth: []
  /meetings/{meetingId}/recordings/registrants/questions:
    get:
      tags:
        - Cloud Recording
      summary: Get registration questions
      description: |
        For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.

        Use this API to retrieve a list of questions that are displayed for users to complete when registering to view the recording of a specific meeting.<br>
        **Scopes:** `recording:read:admin`, `recording:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: recordingRegistrantsQuestionsGet
      security:
        - OAuth: []
    patch:
      tags:
        - Cloud Recording
      summary: Update registration questions
      description: |
        For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.

        Use this API to update registration questions that are to be answered by users while registering to view a recording.<br>
        **Scopes:** `recording:write:admin`, `recording:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
      operationId: recordingRegistrantQuestionUpdate
      security:
        - OAuth: []
  /metrics/meetings:
    get:
      tags:
        - Dashboards
      summary: List meetings
      description: |-
        List total live or past meetings that occurred during a specified period of time. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.<br>
        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br><br>
        **Prerequisites:** <br>
        * Business or a higher plan.<br><br>
      operationId: dashboardMeetings
      security:
        - OAuth: []
  /metrics/meetings/{meetingId}:
    get:
      tags:
        - Dashboards
      summary: Get meeting details
      description: |-
        Get details on live or past meetings. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.  <br>
        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:** <br>
        * Business or a higher plan.
      operationId: dashboardMeetingDetail
      security:
        - OAuth: []
  /metrics/meetings/{meetingId}/participants:
    get:
      tags:
        - Dashboards
      summary: List meeting participants
      description: |-
        Get a list of participants from live or past meetings.<br><br>
        If you do not provide the `type` query parameter, the default value will be set to `live` and thus, you will only see metrics for participants in a live meeting, if any meeting is currently being conducted. To view metrics on past meeting participants, provide the appropriate value for `type`. <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.

        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:** Business or a higher plan.
      operationId: dashboardMeetingParticipants
      security:
        - OAuth: []
  /metrics/meetings/{meetingId}/participants/{participantId}/qos:
    get:
      tags:
        - Dashboards
      summary: Get meeting participant QoS
      description: |-
        Retrieve the quality of service for participants from live or past meetings. This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields. <br><br>
        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: dashboardMeetingParticipantQOS
      security:
        - OAuth: []
  /metrics/meetings/{meetingId}/participants/qos:
    get:
      tags:
        - Dashboards
      summary: List meeting participants QoS
      description: |-
        Get a list of meeting participants from live or past meetings along with the quality of service they recieve during the meeting such as connection quality for sending/receiving video, audio, and shared content.<br>If you do not provide the `type` query parameter, the default value will be set to `live` and thus, you will only see metrics for participants in a live meeting, if any meeting is currently being conducted. To view metrics on past meeting participants, provide the appropriate v[...]
        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:** <br>
        * Business or a higher plan.
      operationId: dashboardMeetingParticipantsQOS
      security:
        - OAuth: []
  /metrics/meetings/{meetingId}/participants/sharing:
    get:
      tags:
        - Dashboards
      summary: Get sharing/recording details
      description: |-
        Retrieve the sharing and recording details of participants from live or past meetings.<br>
        **Scopes:** `dashboard_meetings:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:** <br>
        * Business or a higher plan.
      operationId: dashboardMeetingParticipantShare
      security:
        - OAuth: []
  /metrics/webinars:
    get:
      tags:
        - Dashboards
      summary: List webinars
      description: |+
        List all the live or past webinars from a specified period of time. <br><br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>
        **Prerequisites:**<br>
        * Business, Education or API Plan with Webinar add-on.


      operationId: dashboardWebinars
      security:
        - OAuth: []
  /metrics/webinars/{webinarId}:
    get:
      tags:
        - Dashboards
      summary: Get webinar details
      description: |+
        Retrieve details from live or past webinars.<br><br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Business, Education or API Plan with Webinar add-on.

      operationId: dashboardWebinarDetail
      security:
        - OAuth: []
  /metrics/webinars/{webinarId}/participants:
    get:
      tags:
        - Dashboards
      summary: Get webinar participants
      description: |+
        Retrieve details on participants from live or past webinars.<br><br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Business, Education or API Plan with Webinar add-on.

      operationId: dashboardWebinarParticipants
      security:
        - OAuth: []
  /metrics/webinars/{webinarId}/participants/{participantId}/qos:
    get:
      tags:
        - Dashboards
      summary: Get webinar participant QoS
      description: |
        Retrieve details on the quality of service that participants from live or past webinars recieved.<br>This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields.<br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` <br>
        **Prerequisites:** <br>
        * Business, Education or API Plan with Zoom Rooms set up.
      operationId: dashboardWebinarParticipantQOS
      security:
        - OAuth: []
  /metrics/webinars/{webinarId}/participants/qos:
    get:
      tags:
        - Dashboards
      summary: List webinar participant QoS
      description: |+
        Retrieve a list of participants from live or past webinars and the quality of service they received.<br>This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields.<br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**
        * Business, Education or API Plan with Webinar add-on.

      operationId: dashboardWebinarParticipantsQOS
      security:
        - OAuth: []
  /metrics/webinars/{webinarId}/participants/sharing:
    get:
      tags:
        - Dashboards
      summary: Get sharing/recording details
      description: |+
        Retrieve the sharing and recording details of participants from live or past webinars. <br><br>
        **Scopes:** `dashboard_webinars:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` <br>
        **Prerequisites:**<br>
        * Business, Education or API Plan with Webinar add-on.

      operationId: dashboardWebinarParticipantShare
      security:
        - OAuth: []
  /metrics/zoomrooms:
    get:
      tags:
        - Dashboards
      summary: List Zoom Rooms
      description: |+
        List information on all Zoom Rooms in an account.<br><br>
        **Scopes:** `dashboard_zr:read:admin`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>
         **Prerequisites:**<br>
        * Business, Education or API Plan with Zoom Rooms set up.


      operationId: dashboardZoomRooms
      security:
        - OAuth: []
  /metrics/zoomrooms/{zoomroomId}:
    get:
      tags:
        - Dashboards
      summary: Get Zoom Rooms details
      description: |
        The Zoom Rooms dashboard metrics lets you know the type of configuration a Zoom room has and details on the meetings held in that room.

        Use this API to retrieve information on a specific room.<br><br>
        **Scopes:** `dashboard_zr:read:admin`<br> <br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`**Prerequisites:**<br>
        * Business, Education or API Plan with Zoom Rooms set up.
      operationId: dashboardZoomRoom
      security:
        - OAuth: []
  /metrics/crc:
    get:
      tags:
        - Dashboards
      summary: Get CRC port usage
      description: |-
        A Cloud Room Connector allows H.323/SIP endpoints to connect to a Zoom meeting.

        Use this API to get the hour by hour CRC Port usage for a specified period of time. <aside class='notice'>We will provide the report for a maximum of one month. For example, if "from" is set to "2017-08-05" and "to" is set to "2017-10-10", we will adjust "from" to "2017-09-10".</aside><br><br>
        **Prerequisites:**<br>
        * Business, Education or API Plan.
        * Room Connector must be enabled on the account.<br><br>
        **Scopes:** `dashboard_crc:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: dashboardCRC
      security:
        - OAuth: []
  /metrics/im:
    get:
      tags:
        - Dashboards
      summary: Get IM metrics
      description: |+
        Get [metrics](https://support.zoom.us/hc/en-us/articles/204654719-Dashboard#h_cc7e9749-1c70-4afb-a9a2-9680654821e4) on how users are utilizing the Zoom Chat Client.<br><br> <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.
        **Scope:** `dashboard_im:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>
        **Prerequisites:**<br>
        * Business or a higher plan.

      operationId: dashboardIM
      security:
        - OAuth: []
  /metrics/client/feedback:
    get:
      tags:
        - Dashboards
      summary: List Zoom meetings client feedback
      description: |-
        Retrieve survey results from [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf). <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.

        **Prerequisites:**
        * Business or higher account
        * [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) enabled.

        **Scope:** `account:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: dashboardClientFeedback
      security:
        - OAuth: []
  /metrics/zoomrooms/issues:
    get:
      tags:
        - Dashboards
      summary: Get top 25 issues of Zoom Rooms
      description: |+
        Get top 25 issues of Zoom Rooms.<br>
        **Scopes:** `dashboard_zr:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
         **Prerequisites:**<br>
        * Business, Education or API Plan with Zoom Rooms set up.

      operationId: dashboardZoomRoomIssue
      security:
        - OAuth: []
  /metrics/issues/zoomrooms:
    get:
      tags:
        - Dashboards
      summary: Get top 25 Zoom Rooms with issues
      description: |-
        Get information on top 25 Zoom Rooms with issues in a month. The month specified with the "from" and "to" range should fall within the last six months.<br>
        **Scope:** `dashboard_home:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Business or a higher plan.
        * Zoom Room must be enabled in the account.
      operationId: dashboardIssueZoomRoom
      security:
        - OAuth: []
  /metrics/issues/zoomrooms/{zoomroomId}:
    get:
      tags:
        - Dashboards
      summary: Get issues of Zoom Rooms
      description: |-
        Get information about the issues that occured on the Top 25 **Zoom Rooms with issues** in an acount. <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.

        **Scope:** `dashboard_home:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:** <br>
        * Business or a higher plan.
        * Zoom Room must be enabled in the account.
      operationId: dashboardIssueDetailZoomRoom
      security:
        - OAuth: []
  /report/daily:
    get:
      tags:
        - Reports
      summary: Get daily usage report
      description: |-
        Retrieve daily report to access the account-wide usage of Zoom services for each day in a given month. It lists the number of new users, meetings, participants, and meeting minutes.<br>
        **Prerequisites**<br>
        * Pro or higher plan.<br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: reportDaily
      security:
        - OAuth: []
  /report/users:
    get:
      tags:
        - Reports
      summary: Get active/inactive host reports
      description: |-
        A user is considered to be an active host during the month specified in the "from" and "to" range, if the user has hosted at least one meeting during this period. If the user didn't host any meetings during this period, the user is considered to be inactive.<br>The Active Hosts report displays a list of meetings, participants, and meeting minutes for a specific time range, up to one month. The month should fall within the last six months.<br>The Inactive Hosts report pulls a list of user[...]
        Use this API to retrieve an active or inactive host report for a specified period of time. The time range for the report is limited to a month and the month should fall under the past six months. <br>You can specify the type of report and date range using the query parameters.<br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or higher plan.
      operationId: reportUsers
      security:
        - OAuth: []
  /report/users/{userId}/meetings:
    get:
      tags:
        - Reports
      summary: Get meeting reports
      description: |-
        Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting) on a past meeting for a specified period of time. The time range for the report is limited to a month and the month should fall under the past six months.

        Meetings will only be returned in the response if the meeting has two or more unique participants.  <br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or higher plan.
      operationId: reportMeetings
  /report/meetings/{meetingId}:
    get:
      tags:
        - Reports
      summary: Get meeting detail reports
      description: |-
        Get a detailed report for a past meeting. <br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan.<br>
      operationId: reportMeetingDetails
      security:
        - OAuth: []
  /report/meetings/{meetingId}/participants:
    get:
      tags:
        - Reports
      summary: Get meeting participant reports
      description: |-
        Get participant report for a past meeting.<br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan.<br>
      operationId: reportMeetingParticipants
      security:
        - OAuth: []
  /report/meetings/{meetingId}/polls:
    get:
      tags:
        - Reports
      summary: Get meeting poll reports
      description: |-
        Retrieve a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) results for a past meeting. <br><br>
        **Scopes:** `report:read:admin`<br>

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan.<br>
      operationId: reportMeetingPolls
      security:
        - OAuth: []
  /report/webinars/{webinarId}:
    get:
      tags:
        - Reports
      summary: Get webinar detail reports
      description: |-
        Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting) containing past webinar details.  <br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or higher plan with Webinar add-on.
      operationId: reportWebinarDetails
      security:
        - OAuth: []
  /report/webinars/{webinarId}/participants:
    get:
      tags:
        - Reports
      summary: Get webinar participant reports
      description: |-
        Get detailed report on each attendee of a webinar.<br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan with Webinar add-on enabled.
      operationId: reportWebinarParticipants
      security:
        - OAuth: []
  /report/webinars/{webinarId}/polls:
    get:
      tags:
        - Reports
      summary: Get webinar poll reports
      description: |-
        Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan with Webinar add-on enabled.
      operationId: reportWebinarPolls
      security:
        - OAuth: []
  /report/webinars/{webinarId}/qa:
    get:
      tags:
        - Reports
      summary: Get webinar Q&A report
      description: |-
        The Question & Answer (Q&A) feature for webinars allows attendees to ask questions during the webinar and for the panelists, co-hosts and host to answer their questions.

        Use this API to retrieve a report on question and answers from past webinars. <br><br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan with Webinar add-on enabled.
      operationId: reportWebinarQA
      security:
        - OAuth: []
  /report/telephone:
    get:
      tags:
        - Reports
      summary: Get telephone reports
      description: |-
        The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports) allows you to view who dialed into meetings via phone (Audio Conferencing or SIP Connected Audio) and which number they dialed into and other details. Use this API to get telephone report for a specified period of time.

        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>**Prerequisites:**<br>
        * Pro or higher plan.
      operationId: reportTelephone
      security:
        - OAuth: []
  /report/cloud_recording:
    get:
      tags:
        - Reports
      summary: Get cloud recording usage report
      description: |-
        Retrieve cloud recording usage report for a specified period. You can only get cloud recording reports that is one day ealier than the current date and for the most recent period of 6 months. The date gap between from and to dates should be smaller or equal to 30 days. <br>
        **Prerequisites**<br>
        * Pro or higher plan.<br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: reportCloudRecording
      security:
        - OAuth: []
  /report/operationlogs:
    get:
      tags:
        - Reports
      summary: Get operation logs report
      description: |-
        The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs) report allows you to audit admin and user activity, such as adding a new user, changing account settings, and deleting recordings.<br>
        Use this API to retrieve operation logs report for a specified period of time.<br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * Pro or higher plan.
      operationId: reportOperationLogs
      security:
        - OAuth: []
  /roles:
    get:
      tags:
        - Roles
      summary: List roles
      description: |-
        List [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) on your account

        **Scopes:** `role:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites** :
        *  Pro or higher plan.
        *  For setting the initial role, you must be the Account Owner.
        *  For subsequent role management, you must be the Account Owner or user with role management permissions.
      operationId: roles
      security:
        - OAuth: []
    post:
      tags:
        - Roles
      summary: Create a role
      description: |-
        Each Zoom user automatically has a role which can either be owner, administrator, or a member.

        **Pre-requisite:**<br>
        * Pro or higher plan.
        * For setting the initial role, you must be the Account Owner.<br>
        * For subsequent role management, you must be the Account Owner or user with role management permissions.<br>
        **Scopes:** `role:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: createRole
      security:
        - OAuth: []
  /roles/{roleId}/members:
    get:
      tags:
        - Roles
      summary: List members in a role
      description: |-
        User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to list all the members that are assigned a specific role.

        **Scope:** `role:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>**Prerequisites:**<br>
        * A Pro or a higher plan.
      operationId: roleMembers
      security:
        - OAuth: []
    post:
      tags:
        - Roles
      summary: Assign a role
      description: |-
        User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to [assign a role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control#h_748b6fd8-5057-4cf4-bbfd-787909c09db0) to members.

        **Scopes:** `role:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites:**<br>
        * A Pro or a higher plan.
      operationId: AddRoleMembers
      security:
        - OAuth: []
  /roles/{roleId}/members/{memberId}:
    delete:
      tags:
        - Roles
      summary: Unassign a role
      description: |-
        User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to unassign a user's role.

        **Scope:** `role:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * A Pro or a higher plan.
      operationId: roleMemberDelete
      security:
        - OAuth: []
  /tsp:
    get:
      tags:
        - TSP
      summary: Get account's TSP information
      description: |-
        Get information on Telephony Service Provider on an account level.<br><br>
        **Scopes:** `tsp:read:admin` <br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

        **Prerequisites:**<br>
        * A Pro or a higher plan.
      operationId: tsp
    patch:
      tags:
        - TSP
      summary: Update account's TSP information
      description: |
        Update information of the Telephony Service Provider set up on an account.<br>
        **Prerequisites**:<br>
        TSP account option should be enabled.<br>
        **Scopes:** `tsp:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: tspUpdate
  /users:
    get:
      tags:
        - Users
      summary: List users
      description: |-
        A Zoom account can have one or more users. Use this API to list users on your account.<br><br>
        **Scopes:** `user:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: users
      security:
        - OAuth: []
    post:
      tags:
        - Users
      summary: Create users
      description: |-
        A Zoom account can have one or more users. Use this API to add a new user to your account.<br><br>
        **Prerequisites:**<br>
        * Pro or higher plan<br><br>
        **Scopes:** `user:write:admin` `user:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userCreate
      security:
        - OAuth: []
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get a user
      description: |-
        A Zoom account can have one or more users. Use this API to view information of a specific user on a Zoom account.<br><br>
        **Scopes:** `user:read:admin` `user:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
        <p style="background-color:#e1f5fe; color:#01579b; padding:8px"> <b>Note: </b>If a user's status is pending, only `id` and `created_at` fields will be returned. The value of `created_at` will be the time at which the API call was made until the user activates their account.</p>
      operationId: user
    delete:
      tags:
        - Users
      summary: Delete a user
      description: |-
        Deleting a user permanently removes them and their data from Zoom. They will be able to create a new Zoom account with the same email address if they have access to it. An account owner or an account admin can transfer meetings, webinars and cloud recordings to another Zoom user before deleting, but if not transferred, they will be permanently deleted.<br><br>

        By default, this API disassociates (unlinks) a user from the associated account. The disassociation will give them their own basic, free Zoom account. It will not be associated with your account, and they will be able to purchase their own licenses. You can transfer the user's data (meetings, webinars and cloud recordings) to another user before disassociation.<br> To permanently delete a user, specify "delete" as the value of the `action` query parameter.
        **Scopes:** `user:write:admin` `user:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userDelete
    patch:
      tags:
        - Users
      summary: Update a user
      description: |-
        Update information on a user's Zoom [profile](https://support.zoom.us/hc/en-us/articles/201363203-My-Profile).<br><br>
        **Scopes:** `user:write:admin` `user:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userUpdate
  /users/me/zak:
    get:
      tags:
        - Users
      summary: Get user's ZAK
      description: |+
        Get User’s Zoom Access Token (ZAK). You can use a ZAK to enable a non-login user to join a meeting on your app. Non-login users do not need to enter their username and password to join meetings.

        **Scope:** `user_zak:read`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: userZak
      security:
        - OAuth: []
  /users/{userId}/assistants:
    get:
      tags:
        - Users
      summary: List user assistants
      description: |-
        List a user's assistants.

        Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br><br>
        **Prerequisites**: <br>
        * Current user as well as the assistant must have Licensed or an On-prem license.
        * Assistants must be under the current user's account.<br>
        **Scopes**: `user:read:admin` `user:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userAssistants
    post:
      tags:
        - Users
      summary: Add assistants
      description: |-
        Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br>Use this API to assign assistants to a user. <br> In the request body, provide either the User ID or th[...]
        **Prerequisite**:
        * The user as well as the assistant must have Licensed or an On-prem license.
        * Assistants must be under the current user's account.<br>
        **Scopes**: `user:write:admin` `user:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userAssistantCreate
      security:
        - OAuth: []
    delete:
      tags:
        - Users
      summary: Delete user assistants
      description: |-
        Delete all assistants of the current user.<br> Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br>
        **Prerequisite**:
        * The user as well as the assistant must have Licensed or an On-prem license.
        * Assistants must be under the current user's account.<br>
        **Scopes**: `user:write:admin` `user:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userAssistantsDelete
  /users/{userId}/assistants/{assistantId}:
    delete:
      tags:
        - Users
      summary: Delete a user assistant
      description: |-
        Delete a specific assistant of a user.
        Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br><br>
        **Prerequisites**:
        * The user as well as the assistant must have Licensed or an On-prem license.
        * Assistants must be under the current user's account.<br>
        **Scopes**: `user:write:admin` `user:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userAssistantDelete
  /users/{userId}/schedulers:
    get:
      tags:
        - Users
      summary: List user schedulers
      description: |-
        List all the schedulers of a user. Schedulers in this context are the users for whom the current user can schedule meetings for.

        For instance, if the current user (i.e., the user whose userId was passed in the path parameter of this API call) is user A, the response of this API will contain a list of user(s), for whom user A can schedule and manage meetings. User A is the assistant of these users and thus has scheduling privilege for these user(s).

        **Prerequisites**:
        * Current user must be under the same account as the scheduler.<br>
        **Scopes**: `user:read:admin` `user:read`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userSchedulers
      security:
        - OAuth: []
    delete:
      tags:
        - Users
      summary: Delete user schedulers
      description: |-
        Delete all of a user's schedulers. Schedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of any user.

        **Prerequisite**: Current user (assistant) must be under the same account as the scheduler.<br>
        **Scopes**: `user:write:admin` `user:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userSchedulersDelete
      security:
        - OAuth: []
  /users/{userId}/schedulers/{schedulerId}:
    delete:
      tags:
        - Users
      summary: Delete a scheduler
      description: |-
        Delete a Scheduler.

        Schedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of this scheduler.

        **Prerequisite**: Current user must be under the same account as the scheduler.<br>
        **Scopes**: `user:write:admin` `user:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userSchedulerDelete
      security:
        - OAuth: []
  /users/{userId}/picture:
    post:
      tags:
        - Users
      summary: Upload a user's profile picture
      description: |-
        Upload a user's profile picture.<br><br>

        Provide `multipart/form-data` as the value of the `content-type` header for this request. This API supports JPEG and PNG file formats.

        **Scopes:** `user:write:admin` `user:write`<br>

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userPicture
  /users/{userId}/settings:
    get:
      tags:
        - Users
      summary: Get user settings
      description: |-
        Retrieve a user's settings.<br><br>
        **Scopes:** `user:read:admin` `user:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userSettings
      security:
        - OAuth: []
    patch:
      tags:
        - Users
      summary: Update user settings
      description: |-
        Update a user's settings.<br><br>
        **Scopes:** `user:write:admin` `user:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userSettingsUpdate
      security:
        - OAuth: []
  /users/{userId}/status:
    put:
      tags:
        - Users
      summary: Update user status
      description: |+
        An account owner or admins can deactivate as well as activate a user in a Zoom account. Deactivating a user will remove all licenses associated with a user. It will prevent the deactivated user from logging into their Zoom account. A deactivated user can be reactivated. Reactivating a user grants the user access to login to their Zoom account.<br> Use this API to either [deactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_6a9bc1c3-d739-4945-[...]

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: userStatus
      security:
        - OAuth: []
  /users/{userId}/password:
    put:
      tags:
        - Users
      summary: Update a user's password
      description: |-
        Update the [password](https://support.zoom.us/hc/en-us/articles/206344385-Change-a-User-s-Password) of a user using which the user can login to Zoom.<br> After this request is processed successfully, an email notification will be sent to the user stating that the password was changed.<br>
        **Scopes:** `user:write:admin` `user:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
        **Prerequisites:**<br>
        * Owner or admin of the Zoom account.
      operationId: userPassword
  /users/{userId}/permissions:
    get:
      tags:
        - Users
      summary: Get user permissions
      description: |-
        Users can be assigned a set of permissions that allows them to access only the pages/information that a user needs to view or edit.<br>

        Use this API to get permissions that have been granted to the user.<br><br>
        **Scopes:** `user:read:admin` `user:read`<br>

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userPermission
  /users/{userId}/pac:
    get:
      tags:
        - PAC
      summary: List a user's PAC accounts
      description: |-
        [Personal Audio Conference](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) (PAC) allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only.<br>Use this API to list a user's PAC accounts.<br><br>
        **Scopes:** `pac:read:admin` `pac:read`<br>
        <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * A Pro or higher plan with [Premium Audio Conferencing](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) add-on.
        * Personal Audio Conference must be enabled in the user's profile.
      operationId: userPACs
  /users/{userId}/tsp:
    get:
      tags:
        - TSP
      summary: List user's TSP accounts
      description: |-
        A user can have a maximum of two TSP accounts. Use this API to list all TSP accounts of a user.<br><br>
        **Scopes:** `tsp:read:admin` `tsp:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: userTSPs
    post:
      tags:
        - TSP
      summary: Add a user's TSP account
      description: |
        Add a user's TSP account.<br><br>
        **Scopes:** `tsp:write:admin` `tsp:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userTSPCreate
  /users/{userId}/tsp/{tspId}:
    get:
      tags:
        - TSP
      summary: Get a user's TSP account
      description: |
        Each user can have a maximum of two TSP accounts. Use this API to retrieve details of a specific TSP account enabled for a specific user.<br><br>
        **Scopes:** `tsp:read:admin` `tsp:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userTSP
    delete:
      tags:
        - TSP
      summary: Delete a user's TSP account
      description: |
        Delete a user's TSP account.<br><br>
        **Scopes:** `tsp:write:admin` `tsp:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userTSPDelete
    patch:
      tags:
        - TSP
      summary: Update a TSP account
      description: |
        Update a user's TSP account.<br><br>
        **Scopes:** `tsp:write:admin` `tsp:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userTSPUpdate
  /users/{userId}/token:
    get:
      tags:
        - Users
      summary: Get a user token
      description: |-
        Retrieve a user's token.<br><br> This token is used for starting meetings with the Client SDK.<br>
        **Scopes:** `user:read:admin` `user:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
        If a user signed into Zoom using Google or Facebook, a null value will be returned for the token. To get the token with this API, ask the user to sign into Zoom using their email and password instead.
      operationId: userToken
      security:
        - OAuth: []
    delete:
      tags:
        - Users
      summary: Revoke a user's SSO token
      description: |-
        Revoke a user's SSO token.<br><br> After calling this API, the SSO user will be logged out of their current Zoom session.<br>
        **Scopes:** `user:write:admin` `user:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userSSOTokenDelete
      security:
        - OAuth: []
  /users/email:
    get:
      tags:
        - Users
      summary: Check a user email
      description: |
        Verify if a user's email is registered with Zoom.<br><br>

        <b>Note: </b>You can successfully check if a user is a registered Zoom user only if the user **signed up for Zoom via email and is within your account.** If you provide an email address of a user who is not in your account, the value of "existed_email" parameter will be "false" irrespective of whether or not the user is registered with Zoom. The response of this API call will not include users who joined Zoom using options such as "Sign in with SSO", "Sign in with Google" or "Sign in wit[...]

        **Scopes:** `user:read:admin` `user:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userEmail
      security:
        - OAuth: []
  /users/{userId}/email:
    put:
      tags:
        - Users
      summary: Update a user's email
      description: |-
        Change a user's [email address](https://support.zoom.us/hc/en-us/articles/201362563-How-Do-I-Change-the-Email-on-My-Account-) on a Zoom account that has managed domain set up.<br>If the Zoom Account in which the user belongs, has multiple [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Domain-), the email to be updated must match one of the managed domains.<br>
        **Scopes:** `user:write:admin` `user:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        >  Note: A user's email address can only be changed for a maximum of 3 times in a day(24 hours).
        **Prerequisite:**<br>
        * Managed domain must be enabled in the account.
        * The new email address should not already exist in Zoom.
      operationId: userEmailUpdate
  /users/vanity_name:
    get:
      tags:
        - Users
      summary: Check a user's PM room
      description: |-
        A personal meeting room is a virtual meeting room that can be permanently assigned to a user.
        Use this API to check if a personal meeting room with the given name exists or not.<br><br>
        **Scopes:** `user:read:admin` `user:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: userVanityName
  /users/{userId}/webinars:
    get:
      tags:
        - Webinars
      summary: List webinars
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br> Use this API to list all the webinars that are scheduled by or on-behalf a user (Webinar host).<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br> <br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
        **Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinars
      security:
        - OAuth: []
    post:
      tags:
        - Webinars
      summary: Create a webinar
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>Use this API to schedule a Webinar for a user (host).<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinarCreate
      security:
        - OAuth: []
  /webinars/{webinarId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>Use this API to get details of a scheduled webinar.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>**Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinar
      security:
        - OAuth: []
    delete:
      tags:
        - Webinars
      summary: Delete a webinar
      description: |-
        Delete a Webinar.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinarDelete
      security:
        - OAuth: []
    patch:
      tags:
        - Webinars
      summary: Update a webinar
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>
        Use this API to make updates to a scheduled Webinar.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinarUpdate
      security:
        - OAuth: []
  /past_webinars/{webinarId}/participants:
    get:
      tags:
        - Webinars
      summary: List webinar participants
      description: |+
        Use this API to list all the participants who attended a webinar hosted in the past. <br>

        **Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.<br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>
        <br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>



      operationId: listWebinarParticipants
  /webinars/{webinarId}/status:
    put:
      tags:
        - Webinars
      summary: Update webinar status
      description: |-
        Update a webinar's status. Use this API to end an ongoing webinar.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * The account must hold a valid [Webinar plan](https://zoom.us/webinar).
      operationId: webinarStatus
      security:
        - OAuth: []
  /webinars/{webinarId}/panelists:
    get:
      tags:
        - Webinars
      summary: List panelists
      description: |-
        Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a Webinar.

        Use this API to list all the panelists of a Webinar.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br>
      operationId: webinarPanelists
      security:
        - OAuth: []
    post:
      tags:
        - Webinars
      summary: Add panelists
      description: |-
        Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a webinar.<br>Use this API to [add panelists](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_7550d59e-23f5-4703-9e22-e76bded1ed70) to a scheduled webinar.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>


        **Prerequisites:**
        * Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br>
      operationId: webinarPanelistCreate
      security:
        - OAuth: []
    delete:
      tags:
        - Webinars
      summary: Remove panelists
      description: |-
        Remove all the panelists from a Webinar.<br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br>
      operationId: webinarPanelistsDelete
      security:
        - OAuth: []
  /webinars/{webinarId}/panelists/{panelistId}:
    delete:
      tags:
        - Webinars
      summary: Remove a panelist
      description: |-
        [Remove](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_de31f237-a91c-4fb2-912b-ecfba8ec5ffb) a single panelist from a webinar.<br> You can retrieve the `panelistId` by calling **List Panelists API**.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>


        **Prerequisites:**<br>
        * Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br>
      operationId: webinarPanelistDelete
      security:
        - OAuth: []
  /webinars/{webinarId}/registrants:
    get:
      tags:
        - Webinars
      summary: List webinar registrants
      description: |+
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>
        Use this API to list all the users that have registered for a webinar.<br><br>
        **Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.<br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

      operationId: webinarRegistrants
      security:
        - OAuth: []
    post:
      tags:
        - Webinars
      summary: Add a webinar registrant
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>Use this API to create and submit the registration of a user for a webinar.<[...]
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**
        * Pro or higher plan with a Webinar Add-on.
      operationId: webinarRegistrantCreate
      security:
        - OAuth: []
  /webinars/{webinarId}/batch_registrants:
    post:
      tags:
        - Webinars
      summary: Perform batch registration
      description: |+
        Use this API to register up to 30 registrants at once for a scheduled webinar that requires [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration). <br>

        **Prerequisites:**<br>
        * The webinar host must be a Licensed user.
        * The webinar should be of type `5`, i.e., it should be a scheduled webinar. Other types of webinars are not supported by this API.<br><br>
        **Scope:** `webinar:write`, `webinar:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>







      operationId: addBatchWebinarRegistrants
      security:
        - OAuth: []
        - Bearer: []
  /webinars/{webinarId}/registrants/status:
    put:
      tags:
        - Webinars
      summary: Update registrant's status
      description: |+
        Update a webinar registrant's status. Using this API, you can specify whether you want to approve a registration, deny a registration or cancel a previously approved registration.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

      operationId: webinarRegistrantStatus
      security:
        - OAuth: []
  /past_webinars/{webinarId}/instances:
    get:
      tags:
        - Webinars
      summary: List past webinar instances
      description: |+
        List past webinar instances.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: pastWebinars
      security:
        - OAuth: []
  /webinars/{webinarId}/polls:
    get:
      tags:
        - Webinars
      summary: 'List a webinar''s polls '
      description: |+
        List all the [polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) of a Webinar.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarPolls
      security:
        - OAuth: []
    post:
      tags:
        - Webinars
      summary: Create a webinar's poll
      description: |+
        Create a [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) for a webinar.<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarPollCreate
      security:
        - OAuth: []
  /webinars/{webinarId}/polls/{pollId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar poll
      description: |+
        Get a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) details.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarPollGet
      security:
        - OAuth: []
    put:
      tags:
        - Webinars
      summary: Update a webinar poll
      description: |+
        Update a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarPollUpdate
      security:
        - OAuth: []
    delete:
      tags:
        - Webinars
      summary: Delete a webinar poll
      description: |+
        Delete a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarPollDelete
      security:
        - OAuth: []
  /webinars/{webinarId}/registrants/questions:
    get:
      tags:
        - Webinars
      summary: List registration questions
      description: |+
        Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to list registration questions and fields that are to be answered by users while registering for a Webinar.<br>
        **Prerequisites:**<br>
        * Pro or higher plan with a Webinar Add-on.
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: webinarRegistrantsQuestionsGet
      security:
        - OAuth: []
    patch:
      tags:
        - Webinars
      summary: Update registration questions
      description: |+
        Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to update registration questions and fields of a scheduled Webinar that are to be answered by users while registering for a Webinar.<br><br>
        **Prerequisites:**<br>
        * Pro or higher plan with a Webinar Add-on.
        * Registration option for Webinar should be set as required to use this API.
        **Scopes:** `webinar:write:admin` `webinar:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: webinarRegistrantQuestionUpdate
      security:
        - OAuth: []
  /im/chat/messages:
    post:
      tags:
        - Chatbot Messages
      summary: Send chatbot messages
      description: |-
        Send chatbot messages from your marketplace chatbot app.<br><br>
        **Scopes:** `imchat:bot`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Authorization Flow**: Client Credentials Flow<br><br>
        To get authorized, make a POST request to `/oauth/token` endpoint with grant type as `client_credentials`. <br>Use `https://api.zoom.us/oauth/token?grant_type=client_credentials` as the endpoint for the request.
        You will need to send your ClientID and Secret as a Basic base64 encoded AUthorization header. Ex. `Basic base64Encode({client_id}:{client_sceret})`<br><br> Next, use the token recieved (access_token) as a bearer token while making the POST /im/chat/messages request to send chatbot messages.<br><br>
        Learn more about how to authorize chatbots in the [Chatbot Authorization](https://marketplace.zoom.us/docs/guides/chatbots/authorization) guide.
      operationId: sendchatbot
      security:
        - Client Credentials: []
  /im/chat/messages/{message_id}:
    put:
      tags:
        - Chatbot Messages
      summary: Edit a chatbot message
      description: |-
        Edit a message that was [sent](https://marketplace.zoom.us/docs/api-reference/zoom-api/im-chat/sendchatbot) by your Chatbot app.<br> After sending a message using the Send Chatbot Message API, you must store the messageId returned in the response so that you can make edits to the associated message using this API.

        **Scope:** `imchat:bot`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Authorization Flow**: Client Credentials Flow<br><br>
        To get authorized, make a POST request to `/oauth/token` endpoint with grant type as `client_credentials`. <br>Use `https://api.zoom.us/oauth/token?grant_type=client_credentials` as the endpoint for the request.
        You will need to send your ClientID and Secret as a Basic base64 encoded AUthorization header. Ex. `Basic base64Encode({client_id}:{client_sceret})`<br><br> Next, use the token received (access_token) as a bearer token while making the PUT /im/chat/messages/{message_id} request to edit a chatbot message.<br><br>
        Learn more about how to authotize chatbots in the [Chatbot Authorization](https://marketplace.zoom.us/docs/guides/chatbots/authorization) guide.
      operationId: editChatbotMessage
      security:
        - Client Credentials: []
    delete:
      tags:
        - Chatbot Messages
      summary: Delete a chatbot message
      description: |-
        Delete a message that was sent by your chatbot app.<br><br> **Scopes:** `imchat:bot`<br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>**Authorization Flow**: Client Credentials Flow<br><br>To get authorized, make a POST request to `/oauth/token` endpoint with grant type as `client_credentials`. <br>Use `https://api.zoom.us/oauth/token?grant_type=client_credentials` as the endpoint for the request.
        You will need to send your ClientID and Secret as a Basic base64 encoded AUthorization header. Ex. `Basic base64Encode({client_id}:{client_sceret})`<br><br> Next, use the token received (access_token) as a bearer token while making the DELETE /im/chat/messages/{message_id} request to delete a message.<br><br>
        Learn more about how to authotize chatbots in the [Chatbot Authorization](https://marketplace.zoom.us/docs/guides/chatbots/authorization) guide.
      operationId: deleteAChatbotMessage
      security:
        - Client Credentials: []
  /meetings/{meetingId}/invitation:
    get:
      tags:
        - Meetings
      summary: Get meeting invitation
      description: |+
        Retrieve the meeting invite note that was sent for a specific meeting.<br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingInvitation
      security:
        - OAuth: []
  /meetings/{meetingId}/livestream:
    get:
      tags:
        - Meetings
      summary: Get live stream details
      description: |+
        Zoom allows users to [live stream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to get a meeting's live stream configuration details such as Stream URL, Stream Key and Page URL.<br><br>
        **Prerequisites:**<br>
        * Meeting host must be a licensed user with a Pro or higher plan.<br>
        * Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5) for the meeting.<br><br>
        **Scopes:** `meeting:read:admin` `meeting:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`



      operationId: getLiveStreamDetails
    patch:
      tags:
        - Meetings
      summary: Update a live stream
      description: |+
        Zoom allows users to [live stream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to update a meeting's live stream information.<br><br>
        **Prerequisites:**<br>
        * Meeting host must have a Pro license.<br>
        **Scopes:** `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


      operationId: meetingLiveStreamUpdate
      security:
        - OAuth: []
  /meetings/{meetingId}/livestream/status:
    patch:
      tags:
        - Meetings
      summary: Update Live Stream Status
      description: |+
        Zoom allows users to [live stream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to update the status of a meeting's live stream.<br><br>
        **Prerequisites:**<br>
        * Meeting host must have a Pro license.<br>
        **Scopes:** `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: meetingLiveStreamStatusUpdate
      security:
        - OAuth: []
  /metrics/client/feedback/{feedbackId}:
    get:
      tags:
        - Dashboards
      summary: Get zoom meetings client feedback
      description: |-
        Retrieve detailed information on a [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf). <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.

        **Prerequisites:**
        * Business or higher account
        * [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) enabled.

        **Scope:** `dashboard_home:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`

        `
      operationId: dashboardClientFeedbackDetail
      security:
        - OAuth: []
  /im/users/{userId}/chat/messages:
    get:
      tags:
        - IM Chat
      summary: Get user’s IM messages
      description: |-
        Get IM Chat messages for a specified period of time. <aside>Note: This API only supports Oauth2.</aside><br><br>
        **Scopes:** `imchat:read`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>

        Please see the [announcements page related to this deprecation.](https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#im-api-notice)
      operationId: listimmessages
      deprecated: true
      security:
        - OAuth: []
  /im/users/me/chat/messages:
    post:
      tags:
        - IM Chat
      summary: Send IM messages
      description: |-
        Send chat message to a user. <aside>Note: This API only supports OAuth 2.0.</aside><br><br>**Scope:** `imchat:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: sendimmessages
      deprecated: true
      security:
        - OAuth: []
  /webinars/{webinarId}/registrants/{registrantId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar registrant
      description: |-
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>Use this API to get details on a specific user who has registered for the We[...]
        **Scopes:** `webinar:read:admin` `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites:**<br>
        * The account must have a Webinar plan.
      operationId: webinarRegistrantGet
      security:
        - OAuth: []
    delete:
      tags:
        - Webinars
      summary: Delete a webinar registrant
      description: |-
        Delete a webinar registrant.<br><br>
        **Scopes**: `webinar:write:admin` `webinar:write`<br>
         <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: deleteWebinarRegistrant
  /phone/users/{userId}:
    get:
      tags:
        - Phone
      summary: Get user's profile
      description: |-
        Retrieve a user's [zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) profile.

        **Scopes:** `phone:read`, `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


        **Prerequisites** :
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: phoneUser
      security:
        - OAuth: []
    patch:
      tags:
        - Phone
      summary: Update user's profile
      description: |-
        Update a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051-Zoom-Phone) user's profile.

        **Scopes:** `phone:write` `phone:write:admin`  <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: updateUserProfile
      security:
        - OAuth: []
  /accounts/{accountId}/phone/settings:
    patch:
      tags:
        - Phone
      summary: Update BYOC settings
      description: |-
        Only [master account owners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) can use this API to enable BYOC(Bring your own carrier) option for a sub account.<br>

        **Scope**:<br>
        * `phone:master` <br>

        **Prerequisites**: <br>
        * Business or enterprise Account.<br>
      operationId: updatePhoneSettings
      security:
        - OAuth: []
  /phone/users/{userId}/settings:
    get:
      tags:
        - Phone
      summary: Get user's settings
      description: |-
        Retrieve a user's zoom phone profile [settings](https://support.zoom.us/hc/en-us/articles/360021325712-Configuring-Settings).

        **Scopes:** `phone:read`, `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: phoneUserSettings
      security:
        - OAuth: []
  /phone/setting_templates:
    get:
      tags:
        - Phone
      summary: List setting templates
      description: |+
        This API lets you retrieve a list of all the phone template settings previously created.
        <br>
        **Scope**:<br>
        * `phone:read:admin` or `phone:read`
        <br>**Prerequisites**: <br>
        1. Business or enterprise Account
        2. A Zoom Phone license

        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: listSettingTemplates
      security:
        - OAuth: []
    post:
      tags:
        - Phone
      summary: Add a setting template
      description: |-
        This API lets you create a Zoom Phone setting template for an account. Template type includes **User**, **Auto Receptionist**, or **Call Queue**. Settings include profile, policy and user settings. After creating a phone template, the settings defined via this request will become the default settings for an account.
        <br><br>
        **Scope**:
        * `phone:write:admin` `phone:write`


        **Prerequisites**:
        1. Business or enterprise Zoom account
        2. A Zoom Phone license

        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>


        <br>
      operationId: addSettingTemplate
  /phone/setting_templates/{templateId}:
    get:
      tags:
        - Phone
      summary: Get setting template details
      description: |+
        This API lets you retrieve a specific account phone template previously created. <br>

        **Scope**: <br>
        * `phone:write:admin` or `phone:write`

        **Prerequisites**: <br>
        1. Business or Enterprise Account
        2. A Zoom Phone license
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: getSettingTemplate
      security:
        - OAuth: []
    patch:
      tags:
        - Phone
      summary: Update a setting template
      description: |+
        Use this API to update or modify profile settings for the phone template. Template type includes **User**, **Auto Receptionist**, or **Call Queue**. After you've modified a template, click **User Settings** to set up settings for Call Handling, Desk Phone, and Others. <br>

        **Scope**:<br>
        * `phone:write:admin` or `phone:write`

        **Prerequisites**: <br>
        1. Business or Enterprise Account
        2. A Zoom Phone license
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: updateSettingTemplate
      security:
        - OAuth: []
  /phone/users/{userId}/call_logs:
    get:
      tags:
        - Phone
      summary: Get user's call logs
      description: |-
        Retrieve a [zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) user's call logs.

        **Scopes:** `phone:read`, `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: phoneUserCallLogs
      security:
        - OAuth: []
  /phone/users/{userId}/recordings:
    get:
      tags:
        - Phone
      summary: Get user's recordings
      description: |-
        Retrieve a user's zoom [phone recordings](https://support.zoom.us/hc/en-us/articles/360021336671-Viewing-Call-History-and-Recordings).
        **Scopes:** `phone:read`, `phone:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: phoneUserRecordings
      security:
        - OAuth: []
  /phone/users/{userId}/voice_mails:
    get:
      tags:
        - Phone
      summary: Get user's voicemails
      description: |-
        Retrieve a user's Zoom Phone voicemails.

        **Scopes:** `phone:read`, `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: phoneUserVoiceMails
      security:
        - OAuth: []
  /past_webinars/{WebinarUUID}/absentees:
    get:
      tags:
        - Webinars
      summary: Get webinar absentees
      description: |-
        List absentees of a webinar.<br><br>
        **Scopes:** `webinar:read:admin` `webinar:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: webinarAbsentees
      security:
        - OAuth: []
  /users/{userId}/tsp/settings:
    patch:
      tags:
        - TSP
      summary: Set global dial-in URL for a TSP user
      description: |
        A global dial-in page can provide a list of global access numbers using which audio conferencing can be conducted. By calling this API, you can set the url for the global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled. <p></p>
        **Scopes:**`tsp:write:admin` `tsp:write`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: tspUrlUpdate
      security:
        - OAuth: []
  /phone/users/{userId}/settings/{settingType}:
    post:
      tags:
        - Phone
      summary: Set up shared access
      description: |-
        Phone users can access [shared voicemail inboxes](https://support.zoom.us/hc/en-us/articles/360033863991-Sharing-and-controlling-access-to-a-voicemail-inbox) in the Zoom desktop client, web portal, or provisioned desk phone. Use this API to define the voicemail access permissions of a user.

        To view these settings in the Zoom web portal, navigate to **Admin >Phone System Management> Users & Rooms**. Click the **Users** tab and select **User Settings**. Scroll down to **Voicemail & Call Recordings**.<br>

        **Scope**:`phone:write:admin`<br>
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>



        **Prerequisites**: <br>
        Business or Enterprise Account
      operationId: addUserSetting
      security:
        - OAuth: []
    delete:
      tags:
        - Phone
      summary: Remove shared access
      description: |+
        Remove the shared voicemail access settings that were previously assigned to a user.

        To view these settings in your Zoom web portal, navigate to **Admin >Phone System Management> Users & Rooms**. Click the **Users** tab and select **User Settings**. Scroll down to **Voicemail & Call Recordings**.<br>

        **Scope**: `phone:write:admin`<br><br>
        **Prerequisites**:<br>
        * Business or enterprise Account<br>
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: deleteUserSetting
      security:
        - OAuth: []
    patch:
      tags:
        - Phone
      summary: Update shared access
      description: |-
        Phone users can access [shared voicemail inboxes](https://support.zoom.us/hc/en-us/articles/360033863991-Sharing-and-controlling-access-to-a-voicemail-inbox) in the Zoom desktop client, web portal, or provisioned desk phone. Use this API to update the voicemail access permissions of a user.

        To view these settings in the Zoom web portal, navigate to **Admin >Phone System Management> Users & Rooms**. Click the **Users** tab and select **User Settings**. Scroll down to **Voicemail & Call Recordings**.<br>

        **Scope**: <br>`phone:write:admin`<br>
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>



        **Prerequisites**:<br>
        Business or Enterprise Account
      operationId: updateUserSetting
      security:
        - OAuth: []
  /phone/call_logs:
    get:
      tags:
        - Phone
      summary: Get account's call logs
      description: |-
        Retrieve [call logs](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-Call-Logs) for an account.

        **Scopes**: `phone:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisite:**<br>
        1. Business or Enterprise account<br>
        2. A Zoom Phone license<br>
        3. Account Owner and a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) with Zoom Phone Management<br>
      operationId: accountCallLogs
      security:
        - OAuth: []
  /phone/users/{userId}/phone_numbers:
    post:
      tags:
        - Phone
      summary: Assign phone number to user
      description: |-
        Assign a [phone number](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers) to a user who has already enabled Zoom Phone.

        **Scopes**: `phone:write` `phone:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: assignPhoneNumber
      security:
        - OAuth: []
  /phone/users/{userId}/phone_numbers/{phoneNumberId}:
    delete:
      tags:
        - Phone
      summary: Unassign phone number
      description: |-
        Unassign [phone number](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers#h_38ba8b01-26e3-4b1b-a9b5-0717c00a7ca6) of a Zoom phone user. <br>

        After assigning a phone number, you can remove it if you don't want it to be assigned to anyone.

        **Scopes**: `phone:write` `phone:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
        3. User must have been previously assigned a Zoom Phone number.
      operationId: UnassignPhoneNumber
      security:
        - OAuth: []
  /phone/users/{userId}/calling_plans:
    post:
      tags:
        - Phone
      summary: Assign calling plan to a user
      description: |+
        Assign [calling plan](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) to a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051-Zoom-Phone) user.

        **Scopes**: `phone:write` `phone:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license

      operationId: assignCallingPlan
      security:
        - OAuth: []
  /phone/users/{userId}/calling_plans/{type}:
    delete:
      tags:
        - Phone
      summary: Unassign user's calling plan
      description: |-
        Unassign a [calling plan](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) that was previously assigned to a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051) user.

        **Scopes**: `phone:write` `phone:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisite:**
        1. Business or Enterprise account
        2. A Zoom Phone license
      operationId: unassignCallingPlan
      security:
        - OAuth: []
  /phone/recordings:
    get:
      tags:
        - Phone
      summary: Get call recordings
      description: |+
        List [call recordings](https://support.zoom.us/hc/en-us/articles/360038521091-Accessing-and-sharing-call-recordings) of an account.<br>

        **Scopes:**<br>
        * `phone:read:admin` `phone:write:admin`

        **Prerequisties:** <br>
        * Pro or higher account with Zoom Phone license.
        * Account owner or admin privileges.

      operationId: getPhoneRecordings
      security:
        - OAuth: []
  /phone/sip_trunk/trunks:
    get:
      tags:
        - Phone
      summary: List BYOC SIP trunks
      description: |+
        List [BYOC SIP trunks](https://zoom.us/docs/doc/Zoom-Bring%20Your%20Own%20Carrier.pdf) that are assigned to an account.

        **Scopes**:<br>
        * `phone:write:admin` or `phone:master`<br>

        **Prerequisites**:<br>
        * Business or Enterprise Account
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: listBYOCSIPTrunk
      security:
        - OAuth: []
  /accounts/{accountId}/phone/sip_trunk/trunks:
    post:
      tags:
        - Phone
      summary: Assign SIP trunks
      description: |+
        Using this API, a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis) owner can assign SIP trunk(s) to a sub account.<br>

        **Scope**:<br>
        * `phone:master` <br>

        **Prerequisites**:<br>
        * Business or enterprise Account.<br>
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: postPhoneSIPTrunk
      security:
        - OAuth: []
  /accounts/{accountId}/phone/sip_trunk/trunks/{sipTrunkId}:
    patch:
      tags:
        - Phone
      summary: Update SIP trunk details
      description: |+
        Update details of a SIP trunk that is assigned to a sub account.<br>

        **Scope**:<br>
        * `phone:master` <br>

        **Prerequisites**:<br>
        Business or Enterprise Account.<br>
        <br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>

      operationId: updatePhoneSIPTrunk
      security:
        - OAuth: []
  /accounts/{accountId}/plans/base/status:
    patch:
      tags:
        - Billing
      summary: Cancel a base plan
      description: |-
        [Cancel a base plan](https://support.zoom.us/hc/en-us/articles/203634215-How-Do-I-Cancel-My-Subscription-) for a sub account.

        This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>

        **Scopes**: `billing:master`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
        **Prerequisites:**<br>
        * The sub account must have a Pro or a higher plan.
      operationId: accountPlanBaseDelete
  /accounts/{accountId}/plans/addons/status:
    patch:
      tags:
        - Billing
      summary: Cancel additional plans
      description: |-
        [Cancel additional plan](https://support.zoom.us/hc/en-us/articles/203634215-How-Do-I-Cancel-My-Subscription-) of a sub account. The cancellation does not provide refund for the current subscription. The service remains active for the current session.

        This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>

        **Prerequisites:**<br>
        * Pro or a higher plan with master account option enabled.
        * The sub account must be a paid account.<br>
        **Scope:** `billing:master`<br>
      operationId: accountPlanAddonCancel
      security:
        - OAuth: []
  /report/activities:
    get:
      tags:
        - Reports
      summary: Get sign In / sign out activity report
      description: |-
        Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports) of users under a Zoom account.<br>
        **Prerequisites**<br>
        * Pro or higher plan.<br>
        **Scopes:** `report:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: reportSignInSignOutActivities
      security:
        - OAuth: []
  /groups/{groupId}/settings:
    get:
      tags:
        - Groups
      summary: Get a group's settings
      description: |-
        Get settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).
        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getGroupSettings
      security:
        - OAuth: []
    patch:
      tags:
        - Groups
      summary: Update a group's settings
      description: |-
        Update settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).<p style="background-color:#FEEFB3; color:#9F6000"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>
        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateGroupSettings
  /groups/{groupId}/lock_settings:
    get:
      tags:
        - Groups
      summary: Get locked settings
      description: |-
        Retrieve a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members will not be able to modify it individually. <p style="background-color:#FEEFB3; color:#9F6000"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getGroupLockSettings
      security:
        - OAuth: []
    patch:
      tags:
        - Groups
      summary: Update locked settings
      description: |-
        Update a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members will not be able to modify it individually. <p style="background-color:#FEEFB3; color:#9F6000"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>

        **Prerequisite**: Pro, Business, or Education account<br>
        **Scopes**: `group:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: groupLockedSettings
      security:
        - OAuth: []
  /accounts/{accountId}/lock_settings:
    get:
      tags:
        - Accounts
      summary: Get locked settings
      description: |-
        [Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users.
        Use this API to retrieve an account's locked settings.

        **Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts options enabled. <br><br>
        **Prerequisites:**
        * Pro or a higher paid account. <br>

        **Scope**: `account:read:admin`.
        <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>





        **Scope:** account:read:admin
      operationId: getAccountLockSettings
    patch:
      tags:
        - Accounts
      summary: Update locked settings
      description: |-
        [Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users. Use this API to update an account's locked settings.

        **Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts options enabled.<br><br>
        **Prerequisites:**<br>
        * Pro or a higher paid account. <br>

        **Scope:** `account:write:admin`<br>
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
      operationId: updateAccountLockSettings
      security:
        - OAuth: []
  /roles/{roleId}:
    get:
      tags:
        - Roles
      summary: Get role information
      description: |-
        Each Zoom user automatically has a role which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list of privileges.

        Use this API to get information including specific privileges assigned to a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control).<br>
        **Pre-requisite:**<br>
        * A Pro or higher plan.<br>
        * For role management and updates, you must be the Account Owner or user with role management permissions.

        **Scopes:** `role:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: getRoleInformation
      security:
        - OAuth: []
    delete:
      tags:
        - Roles
      summary: Delete a role
      description: |-
        Each Zoom user automatically has a role which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.

        Use this API to delete a role.<br>
        **Pre-requisite:**<br>
        * A Pro or higher plan.<br>
        * For role management and updates, you must be the Account Owner or user with role management permissions.

        **Scopes:** `role:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: deleteRole
      security:
        - OAuth: []
    patch:
      tags:
        - Roles
      summary: Update role information
      description: |-
        Each Zoom user automatically has a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.

        Use this API to change the privileges, name and description of a specific role.<br>
        **Pre-requisite:**<br>
        * A Pro or higher plan.<br>
        * For role management and updates, you must be the Account Owner or user with role management permissions.<br>**Scopes:** `role:write:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: updateRole
      security:
        - OAuth: []
  /accounts/{accountId}/plans/usage:
    get:
      tags:
        - Billing
      summary: Get plan usage
      description: "Get information on usage of [plans](https://marketplace.zoom.us/docs/api-reference/other-references/plans)\
        \ of an account. This API supports regular accounts as well as master and\
        \ sub accounts. To get plan usage of a regular account, use the `account:read:admin`\
        \ scope and provide “me” as the value of the  `accountId` path parameter.\L\
        \LTo get plan usage of a master account, provide the keyword \"me\" as the\
        \ value of the `accountId` path parameter and use the `billing:master` scope.\
        \ To get plan usage of a sub account, provide the actual account Id of the\
        \ sub account as the value of the `accountId` path parameter and use the `billing:master`\
        \ scope. \n\n**Prerequisite**:<br>\nAccount type: master account on a paid\
        \ Pro, Business or Enterprise plan.<br>\n**Scope:** `billing:master` for master\
        \ and sub accounts. `account:read:admin` for regular Zoom accounts.<br>\n\
        \ **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: getPlanUsage
      security:
        - OAuth: []
  /accounts/{accountId}/owner:
    put:
      tags:
        - Accounts
      summary: Update the account owner
      description: |-
        The current account owner can [change the owner of an account](https://support.zoom.us/hc/en-us/articles/115005686983-Change-Account-Owner) to another user on the same account.<br> Use this API to change the owner of a sub account.

        **Prerequisites**: <br>
        * Account owner or admin permissions of an account.
        * The account making this API request must be on a pro or a hiigher plan with [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis) privilege.<br><br>

        **Scopes:**  `account:write:admin` or `account:master`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>


        <br>
      operationId: updateAccountOwner
      security:
        - OAuth: []
  /accounts/{accountId}/users/{userId}/account:
    put:
      tags:
        - Users
      summary: Switch a user's account
      description: |-
        Disassociate a user from one Account and move the user to another Account under the same master account.

        With this API, a user under a master account or a sub account can be moved to another sub account within the same master account. To move a user from a master account to a sub account, use `me` as the value for `accountId`. In this scenario, "me" refers to the Account ID of the master account.

        To move a user from one sub account to another sub account, provide the sub account's Account ID as the value for `accountId`.

        **Prerequisites**:
        * The account should have Pro or a higher plan with master account option enabled.
        * The user whose account needs to be switched should not be an admin or an owner of that account.
        * The user should not have the same [managed domain](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Domain-) as the account owner.

        **Scope:** `user:master`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: switchUserAccount
      security:
        - OAuth: []
  /accounts/{accountId}/recordings:
    get:
      tags:
        - Cloud Recording
      summary: List recordings of an account
      description: |
        List [Cloud Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) available on an Account.

        > To access a password protected cloud recording, add an "access_token" parameter to the download URL and provide [JWT](https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-jwt-app) as the value of the "access_token".
        <br>
        **Prerequisites**:<br>
        * A Pro or a higher paid plan with Cloud Recording option enabled.<br>
        **Scopes**: `recording:read:admin` or `account:read:admin`

        If the scope `recording:read:admin` is used, the Account ID of the Account must be provided in the `accountId` path parameter to list recordings that belong to the Account. This scope only works for sub accounts.

        To list recordings of a master account, the scope must be `account:read:admin` and the value of `accountId` should be `me`.<br>  **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
      operationId: getAccountCloudRecording
      security:
        - OAuth: []
  /webinars/{webinarId}/tracking_sources:
    get:
      tags:
        - Webinars
      summary: Get webinar tracking sources
      description: |
        [Webinar Registration Tracking Sources](https://support.zoom.us/hc/en-us/articles/360000315683-Webinar-Registration-Source-Tracking) allow you to see where your registrants are coming from if you share the webinar registration page in multiple platforms. You can then use the source tracking to see the number of registrants generated from each platform.<br> Use this API to list information on all the tracking sources of a Webinar.<br>
        **Scopes:** `webinar:read:admin`, `webinar:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>
        **Prerequisites**:<br>
        * [Webinar license](https://zoom.us/webinar).
        * Registration must be required for the Webinar.
      operationId: getTrackingSources
      security:
        - OAuth: []
  /rooms/account_profile:
    get:
      tags:
        - Rooms Account
      summary: Get Zoom Room account profile
      description: |-
        Get details on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To get information on an individual Room Profile, use [Get Zoom Room Profile API](https://marketplace.zoom.us/docs/api-reference/zoom-api/rooms/getzrprofile) instead.

        **Prerequisites:**<br>
        * Zoom account owner or Zoom Rooms admin permissions<br>

        **Scopes:** `room:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getZRAccountProfile
      security:
        - OAuth: []
    patch:
      tags:
        - Rooms Account
      summary: Update Zoom Room account profile
      description: |-
        Update information on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To update information on an individual Room Profile, use [Update Zoom Room Profile API](https://marketplace.zoom.us/docs/api-reference/zoom-api/rooms/updatezrprofile) instead.

        **Prerequisites:**<br>
        * Zoom account owner or Zoom Rooms admin permissions<br>

        **Scopes:** `room:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateZRAccProfile
      security:
        - OAuth: []
  /rooms/account_settings:
    get:
      tags:
        - Rooms Account
      summary: Get Zoom Room account settings
      description: |-
        Get details on Account Settings of a Zoom Room. With this API, you can view either the **Account Meeting Settings** or the **Alert Settings** (Client Alert Settings and Notfication Settings) of the Zoom Rooms account. By default, only **Account Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.<br><br>
        **Prerequisites:**<br>
        * Zoom Room licenses
        * Owner or Admin privileges on the Zoom Account.<br>
        **Scopes:** `room:read:admin`<br><br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getZRAccountSettings
      security:
        - OAuth: []
    patch:
      tags:
        - Rooms Account
      summary: Update Zoom Room account settings
      description: |-
        Update account settings applied for Zoom Rooms in a Zoom account. With this API, you can update either the **Account Meeting Settings** or the **Alert Settings** (Client Alert Settings and Notfication Settings) of the Zoom Rooms account by specifying the required setting type in the `setting_type` parameter. To update only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter and to update only **Account Meeting Settings**, specify `meeting` as the value [...]
        **Prerequisites:**<br>
        * Zoom Room licenses
        * Owner or Admin privileges on the Zoom Account.<br>
        **Scopes:** `room:write:admin`<br>

          **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateZoomRoomAccSettings
      security:
        - OAuth: []
  /rooms/locations:
    get:
      tags:
        - Rooms Location
      summary: List Zoom Room locations
      description: |-
        A Zoom account owner or a Zoom Room administrator can establish a [location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to help manage Zoom Rooms that are spread among a variety of locations. Use this API to list the different location types used for Zoom Rooms in an account.<br><br>
        **Prerequisites:**
        * Account owner or admin permissions.
        * Zoom Rooms Version 4.0 or higher<br><br>
        **Scopes:** `room:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listZRLocations
      security:
        - OAuth: []
    post:
      tags:
        - Rooms Location
      summary: Add a location
      description: |-
        Add a location to the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) of Zoom Rooms in an account.

        **Prerequisites:**
        * Account owner or admin permissions.
        * Zoom Rooms Version 4.0 or higher<br><br>
        **Scopes:** `room:write:admin`<br>


         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: addAZRLocation
      security:
        - OAuth: []
  /rooms/locations/{locationId}:
    get:
      tags:
        - Rooms Location
      summary: Get Zoom Room location profile
      description: |-
        Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page that includes information such as name of the location, address, support email, etc. Use this API to retrieve information about a specific Zoom Rooms location type such as information about the city where the Zoom Rooms is located.

        **Prerequisite:**<br>
        * Account owner or admin permission
        * Zoom Rooms version 4.0 or higher<br>
        **Scopes:** `room:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getZRLocationProfile
      security:
        - OAuth: []
    patch:
      tags:
        - Rooms Location
      summary: Update Zoom Room location profile
      description: |-
        Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page that includes information such as name of the location, address, support email, etc. Use this API to update information about a specific Zoom Rooms location type such as information about the city where the Zoom Rooms is located.

        **Prerequisite:**<br>
        * Account owner or admin permission
        * Zoom Rooms version 4.0 or higher<br>
        **Scopes:** `room:write:admin`<br>


         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateZRLocationProfile
      security:
        - OAuth: []
  /rooms/locations/{locationId}/settings:
    get:
      tags:
        - Rooms Location
      summary: Get location settings
      description: |-
        Get information on meeting or alert settings applied to Zoom Rooms located in a specific location. By default, only **Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.<br><br>
        **Prerequisites:**<br>
        * Zoom Room licenses
        * Owner or Admin privileges on the Zoom Account.<br>
        **Scopes:** `room:read:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: getZRLocationSettings
      security:
        - OAuth: []
    patch:
      tags:
        - Rooms Location
[...]
